### ISSUE TITLE
LCM, GCD

### ISSUE THREAD

**Issue by VirdhatchaniKN** [tenstorrent/tt-metal#10033]
Master issue : #9702 
### Op Requirement :

- ElemwiseBinary/ELEMWISE_BINARY_LCM
- ElemwiseBinary/ELEMWISE_BINARY_GCD

**Issues :** 

Implementing one of these ops, can make it easier for the other implementation as their are dependant .We have come up two approaches for GCD
1. Using for loop
```
def custom_gcd(a, b):
    def gcd(x, y):
        min_val = x if x < y else y
        for i in range(min_val, 0, -1):
            if x % i == 0 and y % i == 0:
                return i
        return 1

    return np.array([gcd(int(x), int(y)) for x, y in zip(a, b)])
```
2. Recursive method
```
def custom_gcd(a, b):
    def gcd(x, y):
        if y == 0:
            return x
        else:
            return gcd(y, x % y)

    return np.array([gcd(x, y) for x, y in zip(a, b)])
```

But these methods would involve repetitive loops/calling of a function.

**Comment by mouliraj-mcw** [comment]
Update:

- [@patrickroberts](https://github.com/patrickroberts)' approach works and LCM, GCD function have been completed.
- Working range : [-1000 , 1000] (Does not work for values not within this range due to bfloat16 conversion.
- Impact of bfloat16 for values not within range [-1000 , 1000] : The GCD function relies on both multiplication and subtraction operations, which are affected by the bfloat16 conversion, leading to slight inaccuracies in the results (e.g., off by +1, +2, -1, or -2).

**Comment by VirdhatchaniKN** [comment]
PR Is ready for review : https://github.com/tenstorrent/tt-metal/pull/10241
