### ISSUE TITLE
[Bug Report] work executor accesses an already deleted ttnn::type::Buffer in DeallocateBuffer when the work executor mode is async.

### ISSUE THREAD

**Issue by namhyeong-kim** [tenstorrent/tt-metal#10085]
**Describe the bug**

Let's see ttnn::Buffer destructor code. [https://github.com/tenstorrent/tt-metal/blob/625fe97d183b4f9cbe2d6ca8bc195b1bbff991ee/ttnn/cpp/ttnn/types.hpp#L78](url)
```cpp
class Buffer : public tt::tt_metal::Buffer {
        ~Buffer() {
            this->deallocate();
        }
    private:
        void deallocate() {
            if (this->device() == nullptr or not this->device()->initialized_ or this->size() == 0) {
                return;
            }
            this->set_size(0);
            TT_ASSERT(this->device()->allocator_ != nullptr, "Expected allocator to be initialized!");
            this->device()->push_work([this] () mutable {
                tt::tt_metal::detail::DeallocateBuffer(this);
            });
        }
};
```
When WorkExecutorMode is set to Async and an heap-allocated ttnn::Buffer is destructed, the destructor enqueues `tt::tt_metal::detail::DeallocateBuffer(this);` into in the work_executor's worker queue. After the destructor completes, the Buffer instance is no longer valid because it has been deleted. Despite this, the work_executor pops its worker queue and attempts to execute `tt::tt_metal::detail::DeallocateBuffer(this);`. Inside `DeallocateBuffer`, the work_executor thread accesses member functions of the now-invalid Buffer object. For example, `buffer->device()` is called.

Below is `DeallocateBuffer` code. [https://github.com/tenstorrent/tt-metal/blob/625fe97d183b4f9cbe2d6ca8bc195b1bbff991ee/tt_metal/tt_metal.cpp#L702](url)
```cpp
void DeallocateBuffer(Buffer *buffer) {
    // buffer is invalid. It has been already deleted.
    EnqueueDeallocateBuffer(
        buffer->device()->command_queue(),
        *(buffer->device()->allocator_),
        buffer->address(),
        buffer->buffer_type(),
        false);
}
```

This sequence leads to a segmentation fault in our application, as the work_executor thread is accessing memory that has already been deleted.

**To Reproduce**
It is difficult to reproduce segfault.

**Expected behavior**
work_executor does not attempt to access the Buffer instance after it has been deleted.
**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by tt-asaigal** [comment]
Hey @namhyeong-kim thanks for the detailed bug report :) Changes staged on https://github.com/tenstorrent/tt-metal/pull/10095, no longer have the `deallocate` function asynchronously querying a potentially destroyed buffer object for metadata.

Instead, we extract the required metadata in the main thread, pass it to the worker which then operates directly on the values, instead of the buffer.

I was able to reproduce a segfault/unexpected set of asserts by running `TestAsyncRuntimeBufferDestructor` and adding a significant delay in the worker thread (which ensured that the buffer object was destructed by the time the worker accessed it). With these changes, I no longer see issues.

Please let me know if you still see the segfault after cherry-picking the commit from the PR.

The only thing that needs to be ensured by the user now, is that a buffer object must be alive when the allocate operation is asynchronously called on it (otherwise the worker is assigning an address to a non-existent buffer object.)

**Comment by namhyeong-kim** [comment]
I applied your patch, and no segmentation fault occured.

**Comment by tt-asaigal** [comment]
Great! Can this be closed?

**Comment by namhyeong-kim** [comment]
Yes
