### ISSUE TITLE
t3k failing model perf llama decoder

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#10323]
https://github.com/tenstorrent/tt-metal/actions/runs/9939060510/job/27453376416

tests removed using @skip_for_wormhole_b0("") at pytest level

**Comment by cglagovichTT** [comment]
This looks like the timeout is not being respected. Any advice on how to fix this?

**Comment by ttmchiou** [comment]
Will look into this and get back to you tomorrow

**Comment by cglagovichTT** [comment]
Looks like someone set the timeout for Llama and Falcon perf tests to 10 minutes when they are invoked `tests/scripts/t3000/run_t3000_model_perf_tests.sh`

**Comment by cglagovichTT** [comment]
I would think that we need 30 minutes for this and the falcon tests

**Comment by vtangTT** [comment]
It wasn't timed out after 10 mins because a timeout of `240000 seconds` was set inside `test_llama_perf_decode` that overrides the timeout set at the script level: 

https://github.com/tenstorrent/tt-metal/blob/0e927d7b1963a75d82c3686aa56b773739b70a35/models/demos/t3000/llama2_70b/tests/test_llama_perf_decode.py#L237

![image](https://github.com/user-attachments/assets/61993feb-2ac4-4e36-aea7-a509caaad821)

**Comment by cglagovichTT** [comment]
But the first time that shows up in the logs is
`2024-07-15 14:58:03.564`
and the last time in the logs is `2024-07-15 15:07:54.346`

It timed out after 10 minutes, not 240000 seconds which would be 66 hours.

**Comment by vtangTT** [comment]
It started running `models/demos/t3000/llama2_70b/tests/test_llama_perf_decode.py::test_Llama_perf_host[wormhole_b0-True-gen128-llama2]` at `2024-07-15 15:07:53.549` and that test had a `240000` second timeout, which should be why the workflow was killed by the github timeout

**Comment by cglagovichTT** [comment]
I'm still confused. If it hit my 240000 timeout, it would have timed out after 66 hours. It clearly did not, and it looks like it timed out after 10 minutes of running the test. This makes it seem like we should just change the invocation of the test to have a larger timeout since the `pytest.mark.timeout` is being ignored.

`  env WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest -n auto models/demos/t3000/llama2_70b/tests/test_llama_perf_decode.py -m "model_perf_t3000" --timeout=600 ; fail+=$?
`

**Comment by ttmchiou** [comment]
Is there a reason to have these large pytests timeouts if we have higher level timeouts on the script level?
I believe we had a move to remove all pytest timeouts since we are setting them on the script level here.

It would be easier to debug if we remove lower level timeouts and see if increasing `--timeout=1800` fixes this issue?

thoughts?
@cglagovichTT

**Comment by cglagovichTT** [comment]
You're right, the absurdly long timeout at the pytest level is making this harder to debug. When I fix the issue in CI I'll also bump down the timeout to something reasonable

**Comment by cglagovichTT** [comment]
Fixed this issue by regenerating weight cache on CI. Reenabling the test in branch `cglagovich/10323` if it passes pipelines https://github.com/tenstorrent/tt-metal/actions/runs/9978307425

**Comment by ttmchiou** [comment]
Setting aside why there's a huge timeout, would it still make sense to have two timeouts?
it seems odd to have two timeouts to kill the test
