### ISSUE TITLE
Generate run/measurement CSVs for Mistral and llama3.1-8B single-card demo test

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#10683]

**Comment by skhorasganiTT** [comment]
@mtairum Raising the priority of this to P0 as per the request of @uaydonat

**Comment by mtairum** [comment]
@uaydonat What's the priority order to add to dashboard?

-> Right now I am working on Mixtral demo with 32K sequence length (instead of the current demo with 128) to have the ideal dashboard perf stats.

-> Then the plan was to integrate Mistral7B to the dashboard (and update the demo to it's maximum seqlen as well).

-> Then the same for Llama3.1-8B.

I can change priority of the above if you think we should get Mistral support before.

**Comment by uaydonat** [comment]
Thank you Miguel. Your priority list looks good.  

We are setting P0s on the csv integrations because we want to have all the models in the dashboard very soon.

**Comment by mtairum** [comment]
Now merged to main and in perf dashboard.
