### ISSUE TITLE
moreh: use env var for kernel src search path

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#11004]
Create env var: TT_METAL_KERNEL_PATH
Should work like, eg, LD_LIBRARY_PATH
Kernel compilation will use this as search paths for the kernel bin
This is in additional to TT_METAL_HOME and absolute paths (supported today)

Due date: early September

**Comment by ayerofieiev-tt** [comment]
Today kernels are located within TT_METAL_HOME.
Here is an example of how kernels are specified within a program
https://github.com/tenstorrent/tt-metal/blob/main/ttnn/cpp/ttnn/operations/data_movement/concat/device/concat_program_factory.cpp#L110-L114
Today this assumes that there is a file `ttnn/cpp/ttnn/operations/data_movement/concat/device/kernels/dataflow/reader_height_sharded_width_concat_two_tensors.cpp` relative to the `TT_METAL_HOME`.

There is a customer request to allow that file to be looked up for in different locations.
We want to support an env variable which acts as "include paths" in compilers, so that a file can be looked for in several locations in addition to TT_METAL_HOME

**Comment by sagarwalTT** [comment]
For this issue, I've made a PR that searches for kernel files in `TT_METAL_KERNEL_PATH` when `CreateKernel()` is called. However, when `CompileProgram()` is called, it generates binaries under `TT_METAL_HOME/built/<build key>/kernels`. Should this be modified so that binaries are generated under `TT_METAL_KERNEL_PATH/built/<build key>/kernels` whenever `TT_METAL_KERNEL_PATH` is specified? The problem with generated binaries being under `TT_METAL_KERNEL_PATH/built/<build key>/kernels` whenever `TT_METAL_KERNEL_PATH` is specified is that if a kernel with the same name exists under `TT_METAL_HOME`, that kernel will be used instead and so it doesn't make sense to generate the binary under `TT_METAL_KERNEL_PATH`.

**Comment by razorback3** [comment]
I don't think generating binaries under different directory is required.
