### ISSUE TITLE
Facing hang issue for Llama3.1_8b prefill cases in WH n300

### ISSUE THREAD

**Issue by keerthana-r-mcw** [tenstorrent/tt-metal#11184]
**Describe the bug**
Facing hang issue in prefill demo, prefill submodule tests in WH n300, and the hang occurs during rotary embedding. We are waiting for @yieldthought's response.

**To Reproduce**
1. Checkout the branch [keerthanar/llama31_8b_n300_ttnn](https://github.com/tenstorrent/tt-metal/tree/keerthanar/llama31_8b_n300_ttnn)
2. Follow the steps in the [README.md](https://github.com/tenstorrent/tt-metal/blob/2e4d901de58d821bfa5f4fd977a7c2683c8bb1e5/models/demos/wormhole_n300/README.md)

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Device: WH n300

**Comment by dvartaniansTT** [comment]
@keerthana-r-mcw and @saichandax Mark has been on vacation. For this one we need to find out which op causes the hang/create unit tests. Once we have this sorted out, we can ask Metalium team's support. cc: @mbahnasTT

**Comment by dvartaniansTT** [comment]
an update from MCW: @keerthana-r-mcw confirms the hang issue has been resolved now following the latest changes to the N150 implementation. However, she reports there are other issues. Once @keerthana-r-mcw and @saichandax confirm this issue is fully resolved, we will close it. 

@keerthana-r-mcw please create issues with proper unit tests for the newly faced problems regarding llama3.1-8b N300 bringup

**Comment by keerthana-r-mcw** [comment]
Sure Dalar.

**Comment by yieldthought** [comment]
Can this be closed now?

**Comment by punithsekar** [comment]
Closing this issue since we don't face the hang issue in latest main. Refer [commit](https://github.com/tenstorrent/tt-metal/compare/main...punith/llama31_8b_n300). 
CC: @keerthana-r-mcw
