### ISSUE TITLE
[potential bug] Tests failing on low aiclk freq

### ISSUE THREAD

**Issue by ttmtrajkovic** [tenstorrent/tt-metal#11203]
Machine/build steps:
1. Connect to `sjc-lab-t3004`
2. Clone tt-metal repo
3. Checkout `ppopovic/didt_fixes` branch (this includes single block stagger)
4. Build tt-metal repo

Repro Steps:

1. Run: tt-smi -r 0,1,2,3
2. Run: safemode --enable
3. pytest tests/ttnn/unit_tests/operations/test_add.py - 
   a. this is just to confirm basic functionality and if freq is set (use `safemode --readback` command for that)
4. WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest tests/didt/test_sharded_ff1.py -k "8chips" - 
   a. this will run FF1 with gelu test on 100k iterations

For running workload multiple times at safemode frequency just repeat 4.

Observe if iteration update stops --> hang happened

Additional tools required for running test:
- safemode used to enter safe mode: https://drive.google.com/drive/folders/1rma8_lHK6LQwmxWLlQ8-qtxghShgGVPB, details of tools usage shared https://tenstorrent.slack.com/archives/C07384DMYJC/p1723053359588649?thread_ts=1722525383.320089&cid=C07384DMYJC and in this thread
- tt-smi used for board reset: https://github.com/tenstorrent/tt-smi

fyi @jvasilje, @pavlepopovic, @s-jovic, @davorchap, @abhullar-tt

**Comment by pavlepopovic** [comment]
Rebased to yesterday's master, branch with rebase is this one: [ppopovic/rebased_didt_tests](https://github.com/tenstorrent/tt-metal/tree/ppopovic/rebased_didt_tests), and tested on a bunch of machines.
In summary, sharded_ff1 test is failing on a bunch of them, in various safe mode voltages.
Detailed results here: https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?gid=2055361291#gid=2055361291 Labeled as **fixed safe mode (applied on all chips) - 500Mhz + 0.85V/0.90V/0.95V**

Instructions for entering safe mode - mentioned in the issue. Provide --voltage 850 for 0.85V, -voltage 900 for 0.90V etc

If tt-smi reset is needed after a test, safe mode needs to be enabled again following reset.

Instructions for running all 3 tests on rebased branch:
```
// Falcon LM head hang
// Run on all chips
TT_ENABLE_MATMUL_STAGGER=1 WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/demos/falcon7b/tests/test_falcon_hang.py -k "test_reproduce_lm_head_nd_32 and 8chips"
// Run on single chip
TT_ENABLE_MATMUL_STAGGER=1 WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/demos/falcon7b/tests/test_falcon_hang.py -k "test_specific_chip_lm_head_nd_32_t3000 and logical_chip3"

// FF1 - hang
// Run on all chips
TT_ENABLE_MATMUL_STAGGER=1 WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/experimental/falcon_7b/tests/test_reproduce_hang_matmul.py -k "test_reproduce_matmul_2d_hang and ff1-hang and 8chips"
// Run on single chip
TT_ENABLE_MATMUL_STAGGER=1 WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest models/experimental/falcon_7b/tests/test_reproduce_hang_matmul.py -k "test_specific_chip_reproduce_matmul_2d_hang_t3000 and logical_chip5"

// Sharded ff1
// Run on all chips
TT_ENABLE_MATMUL_STAGGER=1 WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest tests/didt/test_sharded_ff1.py -k "test_reproduce_matmul_2d_hang and 8chips"
// Run on single chip
TT_ENABLE_MATMUL_STAGGER=1 WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest tests/didt/test_sharded_ff1.py -k "test_specific_chip_reproduce_matmul_2d_hang_t3000 and logical_chip2"
```

The last one is the one that's causing the most issues with safe mode.

**Comment by tt-aho** [comment]
- On `sjc-lab-t3004`, I am able to reproduce the hang using the 8 chip test. It looks like it happens on mmio chip 3 / remote chip 7 when running. (specifically, the test synchronizes on chip 7 first then chip 3, so it looks like chip 7 hangs since we test that first, but the mmio chip might be dead, so might be actually chip 3 and not 7 that is the issue)
- With watcher enabled, it seems like the mmio chip is dead, as we read 0xffffffff from the board instead of just hanging
- Hanging without watcher also reads 0xffffffff when trying to access through pcie
- I am unable to reproduce the hang just running a single chip, but can reproduce the hang when running with both chip 3/7 at the same time
- The setup runs MM on chip 3/7 in parallel, then blocks. If I make them serial (block after launching on a device) there is no hang
- There is also no hang when I change the MM subblock size to 1x1
- A potential side issue is that on `sjc-lab-t3004`, it looks like mmio chip 2 does not produce deterministic output. All other chips always generate the exact same output compared to the first run with the same input, but chip 2 always has a ND amount of mismatches that changes every iteration (typically < 1000 mismatches out of 18874368 elements, and max difference <~15). This will happen every iteration. Did not look into this further for now
- I am unable to reproduce the hang or mismatch on a different t3k I have `sjc-snva-t3004`

**Comment by ttmtrajkovic** [comment]
Failures on `sjc-lab-3004` or any other system are no longer seen with latest FW releases 80.10.3.0 at 0.85V.
At 0.9V and above, the failures are reproduced with thermal trip.
0.85V is a point of interest for safe mode setting so closing this for now.
