### ISSUE TITLE
Test different start stagger values

### ISSUE THREAD

**Issue by ttmtrajkovic** [tenstorrent/tt-metal#11290]
For failing matmul tests, test with different stagger values on first block of data:
- 0 stagger
- 1/2 length of compute block
- 1.2x length of compute block 

Get the length of compute block in cycles by checking the parameters of the matmul. For every tile, you could use 22 CLK cycles.

This should be tested with:
1. FW 8.10.0.0 ([8.10.0.0](https://www.google.com/url?q=https://www.google.com/url?q%3Dhttps://github.com/tenstorrent/tt-firmware/blob/main/fw_pack-80.10.0.0.fwbundle%26source%3Dgmail-imap%26ust%3D1724037694000000%26usg%3DAOvVaw2DhJk09BsSTt_6Z3TFjrJW&source=gmail-imap&ust=1724038464000000&usg=AOvVaw2n9VHk4EM_j9WAfQYSSFIP))
2. FW with LL disabled, at 1GHz, no margin ([8.9.0.0](https://www.google.com/url?q=https://github.com/tenstorrent/tt-firmware/blob/9fc36a3ba6169849941e7297d01fee387e79b2eb/fw_pack-80.9.0.0.fwbundle&source=gmail-imap&ust=1724038464000000&usg=AOvVaw35EuikJXZ683RhzbLkbpDW))

Next step: for different non-zero stagger, check lower AICLK frequencies in 13.5MHz steps.

Milos

**Comment by ttmtrajkovic** [comment]
Notes 8/20:

- use tracy-provided infrastructure for timestamps dumping
- no point of finishing LM Head as 12k already exceeds block length
- finish other two workloads with missing points, move on to per-block stagger

**Comment by skrsmanovicTT** [comment]
@ttmtrajkovic Steps to test FF1 Sharded with GELU test on T3000 system

- Check out tt-metal repo https://github.com/tenstorrent/tt-metal
- Check out tt-experiment repo https://yyz-gitlab.local.tenstorrent.com/tenstorrent/tt-experiment
- Please set TT_WORK_ROOT env variable to point to directory where your git repos are checked out
- Please follow appropriate section how to setup environment for running tests and logging ARC data (https://yyz-gitlab.local.tenstorrent.com/tenstorrent/tt-experiment/-/blob/main/docs/environments.md#environments-for-experiments) steps are bit different if you are using ird reservation or non ird docker image
- From this point you are set to run tests and monitor ARC data, you can run test manually in one terminal and run ARC data logger in another one with following commands:
    - running test: 
![image](https://github.com/user-attachments/assets/2ffd996e-ec17-40cb-a176-2777def3983a)
    - logging ARC data: ttp didt --args out=out/didt.csv,num_iters=300000
- You can find more about running ARC logger and plotting results here: https://yyz-gitlab.local.tenstorrent.com/tenstorrent/tt-experiment/-/blob/main/docs/jtag.md#didt-sampling
- You can use simple script for test running automation attached, just paste it in tt-metal directory and run it (it should be simple and self explanatory)
[testRunnerSimple.txt](https://github.com/user-attachments/files/16819742/testRunnerSimple.txt)

**Comment by skrsmanovicTT** [comment]
While working on this task several experiments are performed, here is short summary what was done:

- Block execution time measurement and analysis for 3 typical workloads used in di/dt testing scenarios.
- Stagger implementation and analysis for 3 different types of stagger:
  - Stagger only first block of workload
  - Stagger every block of workload
  - Hybrid stagger - stagger every Xth block of workload
- Stagger testing for 3 typical di/dt workloads over different machines and test setups.

### Block execution time measurement and analysis
For di/dt testing 3 typical workloads are used:
1. LM Head (100k+ iterations of matmul with L1 interleaved - LoFi math)
2. FF1 no GELU(100k+ iterations of matmul 2D with L1 sharded and no activation - LoFi math)
3. FF1 with GELU(100k+ iterations of matmul 2D with L1 sharded with GELU activation - HiFi2 math)

[Tracy](https://docs.tenstorrent.com/tt-metal/latest/tt-metalium/tools/tracy_profiler.html) and [Device Program Profiler ](https://docs.tenstorrent.com/tt-metal/latest/tt-metalium/tools/device_program_profiler.html) are used as tools for measuring execution time of blocks within 3 typical workloads. Theoretical (expected) values of execution times are provided by @ttmtrajkovic based on versim execution times. [Spreadsheet](https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?gid=850438254#gid=850438254) provides detailed overview of measured vs expected execution times, most important takeaways from this analysis are:

1. Measured values are longer compared to theoretical.
2. LM head is data movement bounded workload, FF1 without GELU is on border between data movement and compute bound workload, FF1 with GELU(HiFi2) is compute bound workload.

*Action items:

- Analyze why measured execution times are differing from theoretical as this impacts overall performance of Tensix engine greatly.

### Stagger implementation and analysis
Main suspect for causing di/dt related hangs are voltage peaks and droops caused by steep current peaks/droops when compute intensive workload starts and stops execution in math part of Tensix engine. To compensate this behavior and make peaks/drops smaller stagger should delay start of math execution for half of the cores for some amount of time. Since large matmul operations(matmul operations used in 3 typical di/dt workloads) are organized per blocks of data, 3 different stagger types are explored during work on this issue:

1. First block stagger - delay execution of math engine on half of the cores only for the first block of data (LM head have 71 blocks while FF1 with/without GELU have 48 blocks per 1 test iterations).
2. Every block stagger - delay execution of math engine on half of the cores for every block of data.
4. Hybrid stagger - delay execution of math engine on half of the cores for every Xth block of data.

#### First Block Stagger
Values used for testing first block stagger are:

- 0 - no stagger
- ~0.5x of comupte block length
- ~1.2x of compute block length

In theory applying first block stagger should keep first half of the cores out of math execution phase with second half of the cores. This should give us out of phase execution and smaller current peaks/drops that should lead to smaller occurrence of hangs in typical di/dt workloads. First block stagger is tested across different machines (mainly T3K systems) for different stagger values depending on the workload. Detailed overview of result can be found in [spreadsheet](https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?gid=1746059450#gid=1746059450), while main conclusions are listed here:

- di/dt looks like machine specific problem - some systems works even without applying stagger, while 0.5 and 1.2 stagger improved hang ratio (even totally removed hangs on some systems)
- First Block Stagger is not final solution for di/dt workloads since there is still workloads that hangs for every possible variant of single block stagger.

[Tracy](https://docs.tenstorrent.com/tt-metal/latest/tt-metalium/tools/tracy_profiler.html) and [Device Program Profiler ](https://docs.tenstorrent.com/tt-metal/latest/tt-metalium/tools/device_program_profiler.html) helped in better understanding of single block stagger performance in terms of synchronization between cores and delayed activation of math engine on half of the cores. More details analysis of tracy results will be provided separately while main observations are following:

- For LM head and FF1 without GILU workloads(workloads that are mostly data movement bounded) stagger is drifting over time and cores (fist and second half) tends to synchronize math execution after approximately half of the blocks are computed.
- For FF1 with GELU workload (compute bounded workload) stagger is consistent over time - math block execution is out of sync for half of the cores through all blocks.

*Action items:
- Stagger implementation should be analyzed - is it possible to have single block stagger that is not drifting over time in case of data movement bounded workloads.

#### Every Block Stagger
Since First Block Stagger is drifting over time in case of data movement bounded workloads, we decided to try out two more stagger variants, every block stagger and hybrid stagger. Every block stagger should delay execution of every math block on half of the cores. It is expected that Every Block Stagger show some benefit in case of data movement bounded workloads while in case of compute bounded workloads single block stagger should be sufficient for cores execution offset, every block stagger can even lead to core synchronization after some time depending on block and stagger size. Since Every Block Stagger makes no sense on compute bounded workloads(FF1 with GELU) and would cause long delays on FF1 without GILU workload we decided to test it only on LM head workload(where math execution in several times shorter compared to data movement) with following value: 0x, 0.625x and 1.2x math block execution length. Every Block Stagger is tested across different machines (mainly T3K systems), detailed overview of results can be found in [spreadsheet](https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?gid=567991626#gid=567991626) while main results are listed here:

- Every Block Stagger with approximate length of 1.25x math block execution length (in case of LM head it is 3000 cycles) looks like appropriate solution for di/dt problems for LM Head workload scenario.

#### Hybrid Stagger

Every block stagger is not perfect solution for FF1 without GELU workload type since length of compute and data movement blocks are similar and this workload is on border to be compute or data movement bounded. In this workload value of every block stagger would need to be monitored and changed over time in order to prevent cores of returning to sync after some amount of blocks (depending on stager size and block size and count). Based on measurements made during first block stagger analysis we decided to try out simple hybrid approach for testing effectiveness of stagger for this type of workload. We decided to stagger execution of math block on half of the cores for every 20th block - based on time analysis this should keep cores out of sync for reasonable scale of phase (more than 1/3 of block length) for all blocks inside one test iteration. Results overview for hybrid stager can be found in [spreadsheet](https://docs.google.com/spreadsheets/d/10uWtBEkLLEM-h5TuuGQ6HW8AjhXwSjFV-cK3iVFYYIU/edit?gid=1124526169#gid=1124526169) and here are main notes:

- Hybrid Stagger showed improvement of hang ratio on some machines (compared to no stagger or first block stagger variants) but still there are systems that hangs even with this stagger implemented.
- Hybrid Stagger is not final solution for di/dt problems on this type of workload.

*Action item:

- More detailed analysis of FF1 without/with GILU workload is required, this include live scope captures of voltage that should confirm if di/dt is real source of hang. Also other possible hang sources should be considered: ARC stuck, thermal trip, SW issue etc..
- Effectiveness of first block stagger in case of LM Head workload should be tested on more machines.
- If there is more di/dt suspect failure workloads we should isolate them, check workload type and test out some of the proposed stagger variants.

**Comment by ttmtrajkovic** [comment]
All modes of stagger has been added on a testing branch: https://github.com/tenstorrent/tt-metal/tree/skrsmanovic/didt_experiments

Stagger is invoked through command line parameters for LM head and FF1 tests:
```
- TT_MATMUL_STAGGER_TYPE to select stagger type:
    - 0 - no stagger
    - 1 - First Block Stagger: apply stagger on first block only
    - 2 - Every Block Stagger: apply stagger on every block
    - 3 - Hybrid Block Stagger: apply stagger on every 20th block
  - TT_MATMUL_STAGGER_VALUE to select stagger length in number of cycles
```
