### ISSUE TITLE
[Bug Report] Build script seems to unnecessarily re-link ttnn Python and all test binaries on 2nd invocation without changing code

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#12131]
**Describe the bug**
After performing a clean build with the build script on the latest master, running the build script again causes the linking process to start over.

Re-linking not only increases build time but also introduces potential issues, so this needs to be fixed.

**To Reproduce**
1. Go to main branch
2. Run command `./build_metal.sh -b Debug`
3. Run command again `./build_metal.sh -b Debug`
4. Observed that the linking process starts again.

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit dcd47ef7b00b2c16a9c51a470725439cc6ab9294)
- Arch: wormhole_b0

**Comment by razorback3** [comment]
@TT-billteng Can you help me with this issue triage?

**Comment by TT-billteng** [comment]
I've been able to repro, but the funny part is this unnecessary linking only occurs on the 2nd attempt. This doesn't happen on any attempt past the 2nd one.

**Comment by tt-rkim** [comment]
@hschoi4448 do you mind posting a list of the files that seem to relink on 2nd attempt? Just wanted to do some comparisons

**Comment by tt-rkim** [comment]
CMake should output

**Comment by razorback3** [comment]
> CMake should output

Then, no more help needed from hschoi4448?

**Comment by hschoi4448** [comment]
> @hschoi4448 do you mind posting a list of the files that seem to relink on 2nd attempt? Just wanted to do some comparisons

main branch hash: f6fd9b996bba32f5e86f872f17a4efb0612434b3

```C++
cmake --build build_$build_type --target tests > test_log.txt     # <- Can also just run `ninja tests -C build`
cmake --build build_$build_type --target install > install_log.txt   # <- This is a general cmake way, can also just run `ninja install -C build`
```

[first install_log.txt](https://github.com/user-attachments/files/16988970/first.install_log.txt)
[first test_log.txt](https://github.com/user-attachments/files/16988971/first.test_log.txt)
[second install_log.txt](https://github.com/user-attachments/files/16988972/second.install_log.txt)
[second test_log.txt](https://github.com/user-attachments/files/16988973/second.test_log.txt)

**Comment by hschoi4448** [comment]
> @hschoi4448 do you mind posting a list of the files that seem to relink on 2nd attempt? Just wanted to do some comparisons

main branch hash: f6fd9b996bba32f5e86f872f17a4efb0612434b3

```C++
cmake --build build_$build_type --target tests > test_log.txt     # <- Can also just run `ninja tests -C build`
cmake --build build_$build_type --target install > install_log.txt   # <- This is a general cmake way, can also just run `ninja install -C build`
```

[first install_log.txt](https://github.com/user-attachments/files/16988970/first.install_log.txt)
[first test_log.txt](https://github.com/user-attachments/files/16988971/first.test_log.txt)
[second install_log.txt](https://github.com/user-attachments/files/16988972/second.install_log.txt)
[second test_log.txt](https://github.com/user-attachments/files/16988973/second.test_log.txt)

@tt-rkim @razorback3

**Comment by tt-rkim** [comment]
Yes that should be good. I am also testing locally to see what exactly is going on.  Thank you @hschoi4448 

I took a quick look at this. Like @TT-billteng , I only see the re-linking the 2nd time around running `build_metal.sh`. The only binaries I see re-linking are tests. I see this behaviour only on the 2nd time on both release and debug builds.

This seems to happen because of the first `cmake` call, which doesn't do actual building, but prepares the `build` folder with configuration. Only on the 2nd run for an existing `build` folder, something happens during this `cmake` call that forces ninja to think it needs to re-link all the tests. After I used certain ninja options, such as `cmake --build build_Release/ --target tests -- -d explain -t commands` and put these into `build_metal.sh` for the final two cmake calls, I think I have found the answer.

I see that `libtt_metal.so` is considered `dirty` and the reason why is because the `rpath` for it seems to change on the 2nd  `cmake $cmake_cargs` call:

`-Wl,-rpath,/home/rkim/tt-metal/build_Release/lib:/home/rkim/tt-metal/build_Release/_deps/nanomsg-build:/home/rkim/tt-metal/build_Release/_deps/libuv-build:` on first build

vs.

`-Wl,-rpath,/home/rkim/tt-metal/build_Release/_deps/nanomsg-build:/home/rkim/tt-metal/build_Release/_deps/libuv-build:/home/rkim/tt-metal/build_Release/lib:` on second build

I'm not 100% sure this is the cause, but I see `command changed` from the ninja output for `libtt_metal.so` so I'm assuming that's the cause. Those rpaths seem to be the same on first glance - I don't see the difference. It's just the ordering. If ninja knows those are the same, then I am incorrect.

**Comment by razorback3** [comment]
Just a question.
Is the work for this issue still ongoing?

**Comment by tt-rkim** [comment]
Yes, sorry for the delays.
We have made many changes to the CMake system recently. Have you given it another try?

**Comment by hschoi4448** [comment]
Thank you. it fixed now!. @tt-rkim
