### ISSUE TITLE
[Bug Report] `transpose_wh_tile` does not work for fp32 and int32 tiles with `fp32_dest_acc_en=true`

### ISSUE THREAD

**Issue by jeongu-moreh** [tenstorrent/tt-metal#12138]
**Describe the bug**
A low-level kernel function `transpose_wh_tile` does not work for fp32 and int32 tiles with `fp32_dest_acc_en=true`. I think it should work fine in these cases as `transpose_wh_tile` uses `llk_math_eltwise_unary_datacopy` to move data like `copy_tile`, which works fine.

**To Reproduce**
Try to transpose a single tile of type fp32 or int32 with `fp32_dest_acc_en=true` (required to use fp32 and int32) using the following compute kernel:
```cpp
#include <cstdint>

#include "compute_kernel_api/common.h"
#include "compute_kernel_api/eltwise_unary/eltwise_unary.h"
#include "compute_kernel_api/transpose_wh.h"

namespace NAMESPACE {
void MAIN {
    constexpr uint32_t num_tiles = get_compile_time_arg_val(0);

    constexpr uint32_t cb_input = tt::CB::c_in0;
    constexpr uint32_t cb_output = tt::CB::c_out0;

    constexpr uint32_t onetile = 1;
    constexpr uint32_t idst = 0;

    unary_op_init_common(cb_input, cb_output);

    for (uint32_t i = 0; i < num_tiles; i++) {
        cb_wait_front(cb_input, onetile);
        cb_reserve_back(cb_output, onetile);

        tile_regs_acquire();
        unpack_reconfig_data_format_srca(cb_input);
        transpose_wh_init_short(cb_input);
        transpose_wh_tile(cb_input, 0, idst);
        tile_regs_commit();

        tile_regs_wait();
        pack_reconfig_data_format(cb_output);
        pack_tile(idst, cb_output);
        tile_regs_release();

        cb_push_back(cb_output, onetile);
        cb_pop_front(cb_input, onetile);
    }
}
}  // namespace NAMESPACE
```

Result:
* fp32: odd rows are missing
* int32: garbage values

**Expected behavior**
Tiles are transposed properly.

**Comment by ttmtrajkovic** [comment]
@razorback3 , 

Unfortunately, tensix core RTL fundamentally can't do transpose with 32bit formats. This is a hardware limitation and there's no way around it. Blackhole doesn't have it either. We are able to support transposing in tf32 format.

The decision has been made due to pretty large area increase.

TF32 format should be enough for training, but if fp32/int32 transposing is indeed needed then the only option is to implement in-tile transposing through one (or many) triscs by doing just L1 mmio reads and writes. Using tensix is not possible.

Milos

**Comment by jeongu-moreh** [comment]
It's a shame that tensix engine cannot transpose them. This functionality is not necessary for LLMs (but useful) so I would better find a workaround. Thanks.
