### ISSUE TITLE
UNet Shallow data parallel model shows poor end-to-end performance

### ISSUE THREAD

**Issue by esmalTT** [tenstorrent/tt-metal#12716]
### Summary
The profile for UNet on N300 shows first convolution in the model is taking a long time on host. I am not seeing this on single chip. This following image shows a single iterations on N300:

![image (3)](https://github.com/user-attachments/assets/da159f3a-b4f0-43e2-a2bd-5f402b18c682)

For reference, this is what the profile looks like for single chip:

![image (4)](https://github.com/user-attachments/assets/548a5b04-54b7-494d-b761-81b28319dc72)

### Steps to Reproduce
Checkout `esmal/enable-async` and run the following on N300:

```sh
pytest -svv models/experimental/functional_unet/tests/test_unet_perf.py::test_unet_data_parallel_perf_e2e
```

Make sure full grid is enabled: `export WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml`

**Comment by tt-asaigal** [comment]
**Total Op Dispatch Time per iteration: 3.79ms**
**Total Host->Device Data Movement Time (blocking reads): 5.75ms**
**Total Device->Host Data Movement Time (blocking reads): 12ms**

During op dispatch, UNet is bound by the main thread, as show in the image below. Python code (pink) is the bottleneck here, as can be seen by:
1. "Empty" regions introduced between consecutive op calls due to python overhead, causing the worker threads to be starved
2. The fact that for the convolution in the second image, the main thread spends 89us running the cpp op code (green) and 262us on `PY_FUNC_CALL`

![image](https://github.com/user-attachments/assets/56ffd6b1-f547-41ac-807b-d9a66e2659f3)

![image](https://github.com/user-attachments/assets/d77be731-0fcb-408b-9e66-ecdcd0426ceb)

For each op invocation, Python overhead needs to be trimmed as much as possible. I'm not familiar with the details of TTNN op infra, but this should be doable by the TTNN team to speed up eager dispatch.

Another thing to note during op dispatch: we spend 436us calling `create_sharded_memory_config`. That's more than 10% of the current host dispatch time. Can these configs we cached once at the start? This should be a minor change to the model code.

**First Conv on Host and Data Movement**
![image](https://github.com/user-attachments/assets/60045e36-39c6-48c9-96f0-c6d11685ba7d)

Convolution code performs several input tensor queries in the main thread, causing it to block until the worker threads have fully created the input tensor (as seen in the image above, where the main thread waits for workers to write the input to device). This is not ideal, as it further slows down the main thread.

All processing done when configuring the conv op should ideally take place in the worker threads, which will lead to the main thread dispatching ops without synchronizing with workers. This seems like an op-infra issue as well.


Finally, I noticed that using non-blocking reads on yyz-lab-56 was causing worker threads to slow down during op dispatch and host -> device data movement. I think this was happening because the reader thread (`CompletionQueueReader` in tracy) and the worker threads use the same CPU core. With non-blocking reads, the same core will perform reads and op dispatch/writes simultaneously, leading to significant context switching overhead.

When I used blocking reads, I saw the input tensor write time decrease to `5.7ms` which decreased the time for the first convolution. I would recommend using blocking reads for now, since data movement is the main bottleneck overall. In the meantime I will try to find an optimal thread assignment scheme for N300, so that reads and writes can be issued by host in parallel without much overhead.
