### ISSUE TITLE
llama3.1_8b test bug 

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#12741]
**Describe the bug**

running` pytest --capture=tee-sys tests/test_llama_model.py `: 

 the process is killed when the last output (linear) layer of the model is attempted to be loaded onto the device. The relevant line that crashes is at the end of the __init__ of class TtTransformer in demos/wormhole/llama31_8b/tt/llama_model.py, copied below. I can print the tensor size and such on host. Any ideas on how to debug?

        self.output_weight = ttnn.as_tensor(
            state_dict["output.weight"].permute(1, 0),
            device=device,
            layout=ttnn.TILE_LAYOUT,
            dtype=dtype,
            memory_config=ttnn.DRAM_MEMORY_CONFIG,
            cache_file_name=weight_cache_path / "output.weight",
        )

**To Reproduce**
1. Go to Commit hash 516a8917fac17649abbc9052b680894b432b4de6 from main branch. 
2. run `pytest --capture=tee-sys tests/test_llama_model.py `
3. process gets killed! 

**Expected behavior**
test to pass 

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (main branch : 516a8917fac17649abbc9052b680894b432b4de6 )
- N300

**Comment by dvartaniansTT** [comment]
additional info from user: 

I believe the issue may be because the below file path does not exist -- I was not clear what step generates this file. I did try to pass in None as cache_file_name , that did not seem to make a difference.

"Unable to load the tensor from /tt-metal/models/demos/wormhole/llama31_8b/weight_cache_dir/Meta-Llama-3.1-8B-Instruct/tensor_cache_bfp8/output.weight_dtype_BFLOAT8_B_layout_TILE.bin.  The file does not exist."

**Comment by yieldthought** [comment]
This message is fine, the cache will be generated on-demand. The process is probably killed because the host CPU is running out of memory. `test_llama_model.py` loads the full FP32 weights as well as the BFP8 weights and performs inference on the reference model to perform PCC tests. We haven't tested the minimum host DRAM required but I would guess at least 64GB.

To run the test without the reference model and reduce host memory requirements, set `run_ref_pt = False` near line 37.

I recommend running the demo scripts to generate model output, `test_llama_model.py` is really for internal development and CI purposes.

**Comment by dvartaniansTT** [comment]
@yieldthought thanks for the detailed response. I will inform the customer.
