### ISSUE TITLE
Enable full dst synchronization scheme

### ISSUE THREAD

**Issue by rtawfik01** [tenstorrent/tt-metal#13026]
`DstMode::Full` synchronization scheme would help with matmuls with fp32 accumulation, since only 4 tiles can fit for Half dest mode for fp32 dest, but 8 can be stored for full mode instead.

DstMode synchronization scheme was removed from APIs before due to lack of usage. In order to enable this again, we should not expose DstMode in all of the api calls, we should instead have a define generated per compute kernel (similar to chlkc_math_fidelity.h or chlkc_dst_accum_mode.h) and have the llk apis take the DstMode from that define, example in llk_api.h:

```
template <bool out_of_order_output = false, bool untilize = false, bool is_fp32_dest_acc_en = false>
inline void llk_pack(std::uint32_t tile_index, std::uint32_t output, std::uint32_t output_tile_index = 0) {
    std::uint8_t output_id = get_output_id(output);

    static_assert((!(untilize && out_of_order_output)) && "untilize out of order packing is not supported!");

    std::uint32_t pack_tile_addr = get_output_tile_address<out_of_order_output, untilize>(output_id, output_tile_index);

    _llk_pack_<DST_SYNC_MODE, untilize, is_fp32_dest_acc_en>(
        tile_index,
        pack_tile_addr
    );
}
```

Where DST_SYNC_MODE would be generated in the `built/` folder in a define file. 

@ttmtrajkovic fyi
@davorchap has mentioned large math utilization gains from enabling Full mode + fp32 dest, enabling this could potentially aid with other models performance with fp32 dest. It would be helpful to have a single core unit test with the case that gave a performance gain with fp32 dest + Full mode (matmul + sublock [1,5]) so performance can be measured locally.

**Comment by amahmudTT** [comment]
@davorchap @yugaoTT  Do you know which one has higher priority, this full Dst synchronization or the tiny tile sizes which do not have support yet ?

**Comment by yugaoTT** [comment]
@amahmudTT I'm not sure which has higher prio since they are all optimizations for llama, but I assum full Dst synchronization should be eaiser to add, since we know that it works?

**Comment by amahmudTT** [comment]
> @amahmudTT I'm not sure which has higher prio since they are all optimizations for llama
Thanks, yeah I think I am going to start with the Dst sync.

**Comment by amahmudTT** [comment]
Code written so far in branch [amahmud/dst_sync_flag ](https://github.com/tenstorrent/tt-metal/commit/c5280bd9243540462fa5b1e069af128706d3ccf3). will generate a file named ```chlkc_dst_sync_mode.h``` which will either contain a define which is defined as ```DstSync::SyncHalf``` or ```DstSync::SyncFull``` which will be used in the lower level kernels. 

For example ```#define DST_SYNC_MODE DstSync::SyncHalf```

**Comment by amahmudTT** [comment]
Removed/Replaced all the DstSync values from the api files. 

There were some functions which were never used but were called with an extra template parameter passing the value of DstSync::SyncHalf, like  
```llk_math_eltwise_binary_sfpu```. 
 think since they were never used the compiler did not throw an error. 

And there were examples of function calls for the function 
```
template <SfpuType sfpu_op, bool APPROXIMATE, bool IS_INT_SFPU_EN=false>
inline void llk_math_eltwise_unary_sfpu(
```
with the last template argument being passed as DstSync::SyncHalf,  although the last parameter is supposed to be for enabling integer calculation. In this case I removed the last parameter since it already has a default value.

**Comment by amahmudTT** [comment]
All post commit tests seem to pass https://github.com/tenstorrent/tt-metal/actions/runs/11130629019
Next step would be to enable/add sweep tests allowing testing of full dst synchronization.

**Comment by amahmudTT** [comment]
functions like release_dst(tt::DstMode mode) , acquire_dst(tt::DstMode mode) need to be cleaned up as eventually their arguments get ignored. 

default argument values for DstSync in all the third party libraries need to be removed too since someone may call them without passing an argument and it may use the default argument which might be the defined value of DST_SYNC_MODE

But the above two changes will affect too many files and make the PR bigger than what it already is, so I will do that part in a separate PR.

**Comment by amahmudTT** [comment]
All post commit tests after adding sweep tests.
https://github.com/tenstorrent/tt-metal/actions/runs/11171145603

**Comment by amahmudTT** [comment]
The PR https://github.com/tenstorrent/tt-metal/pull/13486 to enable this feature was merged. 
There will be follow up cleanup items 
https://github.com/tenstorrent/tt-metal/issues/13547
https://github.com/tenstorrent/tt-metal/issues/13548
They can be tracked as separate issues. So I guess we can close this one ?

**Comment by amahmudTT** [comment]
All relevant PRs merge closing the issue.
