### ISSUE TITLE
Full FP32 precision eltwise add, for reduction of gradients across model replicas

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#13445]
as per discussion with @ttmtrajkovic 

* option 1: through SFPU (load both operands to DST, and then do SFPU add in full FP32 precision)
* option 2: build an op which takes one operand and unpacks it to DST and then do pack + L1 accumulate in FP32 on another operand

Notes:
- can unpack full FP32 into DST, bypasses src registers and unpacks directly to dst, preserving all bits
- available both in WH and BH
- both options above support full FP32 precision

starting off as P2 as this is not immediately needed, but need to track as we're ramping up data parallel training

in the meantime we can try current FP32 eltwise add, which will use reduced precision TF32 math to perform addition

**Comment by davorchap** [comment]
fyi @yan-zaretskiy and @dmakoviichuk-tt

**Comment by rdjogoTT** [comment]
Option 1 (SFPU) added here: https://github.com/tenstorrent/tt-metal/blob/aa18d6b09bed62f2db6de9b8b2352e35da528a1a/tt_metal/include/compute_kernel_api/eltwise_binary_sfpu.h#L35

Option 2 (L1 Accumulation) is already possible, no LLK changes are needed. The OP would be similar to current unary eltwise SFPU OPs (which already work with FP32). Just don't perform any SFPU kernels and when packing use `pack_reconfig_l1_acc` to configure L1 accumulation. `pack_tile` already has `out_of_order_output` flag which enables packing to the same address multiple times.

@davorchap I think this can be closed since LLK portion is complete.
