### ISSUE TITLE
Values in (2^15, 2^23) are not rounded by rounding ops

### ISSUE THREAD

**Issue by jdh8** [tenstorrent/tt-metal#13544]
Currently, rounding ops ignore values outside range of `i16`, i.e. [-2<sup>15</sup>, 2<sup>15</sup>).

https://github.com/tenstorrent/tt-metal/blob/3d33e8d74287473f6877c4c02d54be5f74f382aa/tt_metal/hw/ckernels/wormhole_b0/metal/llk_api/llk_sfpu/ckernel_sfpu_floor.h#L31-L33

Since there are 24 significand bits (23 explicit) in `f32`, the maximum finite non-integer in `f32` is 2<sup>23</sup> &minus; 0.5.  As a result, non-integers with absolute value in (2<sup>15</sup>, 2<sup>23</sup>) are returned as is and **not** rounded.

Either of the following would solve this issue:
- Work on `i32` instead of `i16`
- A second iteration that works on magnitudes > 2<sup>15</sup>

**Comment by mouliraj-mcw** [comment]
Hi @jdh8 
As mentioned in the C kernel, since support for `float-to-int32` conversion is currently unavailable, we will wait until this support is added.

Hi @rdjogoTT, @rtawfik01 
Is support for float-to-int32 conversion possible?

cc: @eyonland

**Comment by rdjogoTT** [comment]
@mouliraj-mcw I do not believe support for float-to-int32 is going to become available as a single call similar to `float_to_int16`, because the underlying instruction does not support int32 as output to the conversion. We do have a manually implemented conversion that I made for the Typecast OP found here: https://github.com/tenstorrent/tt-llk-wh-b0/blob/eadfdb466dcc738803969f9eda76aacbb33b5ad6/common/inc/sfpu/ckernel_sfpu_typecast.h#L62-L97 
I wouldn't recommend just dropping in this kernel in place of `float_to_int`, because that would be very slow. It would be better to combine the two so that there isn't as much of a perf hit.
