### ISSUE TITLE
[Bug Report] Incorrect Copy Result When Using fp32_dest_acc with dataflow cb

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#13802]
**Describe the bug**
I discovered the bug while testing because I wanted to try using the `dataflow` CB instead of `intermed`.

There are no issues when using bfloat16 tensors.
However, when using the FP32 CB and enabling `fp32_des_acc_en`, the issue occurs.

I modified the existing `moreh_softmax` to create a simple test code for testing purposes.

The test code copies the input of size 1 tile to the temporary CB and then copies it again to the output CB.
In this case, using `intermed` with the temporary CB works without issues, but using the dataflow CB results in incorrect output values.

**To Reproduce**
1. Go to https://github.com/tenstorrent/tt-metal/tree/hyungsuk/bug_dataflow
2. run cmd `pytest tests/ttnn/unit_tests/operations/bug.py`
3. See Result
```Python
input tensor([[0., 3., 1., 0.],
        [3., 3., 3., 3.],
        [1., 3., 1., 2.]], dtype=torch.bfloat16)
output tensor([[  0.,   0.,   0.,   0.],
        [103., 102.,  inf,  inf],
        [ inf,  inf,  inf,  inf]], dtype=torch.bfloat16)
```

**Expected behavior**
The kernel's operation involves copying the input tensor through a temporary tensor to the output. 
Therefore, the values of the input and output should be the same.

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software: cb49c1b4e97b365482edd7bc2647a7136c776cd8
- arch: wormhole_b0

**Additional context**

**Comment by ttmtrajkovic** [comment]
@hschoi4448,
could you please clarify the difference between `intermed` and `dataflow` CB?

**Comment by hschoi4448** [comment]
> @hschoi4448, could you please clarify the difference between `intermed` and `dataflow` CB?

dataflow CB
- tt::CB::dataflow0
- return correct result

intermed CB
- tt::CB::c_intermed0
- return incorrect result

**Comment by razorback3** [comment]
Dataflow CBs and intermediate CBs are defined in here by the Metal developers.
https://github.com/tenstorrent/tt-metal/blob/e5f887e5c54164e93836b5a6d2bd5747fe81f27f/tt_metal/hostdevcommon/kernel_structs.h#L25
https://github.com/tenstorrent/tt-metal/blob/e5f887e5c54164e93836b5a6d2bd5747fe81f27f/tt_metal/hostdevcommon/kernel_structs.h#L45

I think he (Hyungsuk) is trying to use dataflow CBs because he ran out of intermediate CBs.

**Comment by hschoi4448** [comment]
Could you also explain the reason for adding this restriction to the dataflow CB in JIT builds?  
- What are the pros and cons of applying this restriction?
@rdjogoTT

**Comment by rdjogoTT** [comment]
The restrictions on CB types are no longer needed since we moved to tt-metal, they just haven't been removed yet. There is work that has been already started that will update how CBs work and fix this issue as well. I don't yet have a timeline for when that will be finished, but if you need this to work with a very high priority then I can look to add a workaround for now.

**Comment by razorback3** [comment]
@rdjogoTT
If the workaround is prepared, does it have a chance to be merged into the main branch?
Or do we have to maintain it at a local branch?

**Comment by rdjogoTT** [comment]
@razorback3 Good news, the CB work I spoke about above has been given a high priority and is nearly ready. I am helping push it through, and we should have this solved as well soon.

**Comment by rdjogoTT** [comment]
Hey this should be resolved with https://github.com/tenstorrent/tt-metal/pull/14971
Please try to repro again on main
