### ISSUE TITLE
Remove padding along non height/width dims for transpose

### ISSUE THREAD

**Issue by TT-BrianLiu** [tenstorrent/tt-metal#14308]
Need to update transpose hc (and other variants that break apart tiles) to natively output non-padded new batch dims.

**Comment by bbradelTT** [comment]
@ntarafdar 
This will block a lot of reduce work. Could you please triage this issue and provide an estimate for when it could be completed.

**Comment by bbradelTT** [comment]
@sjameelTT yes, reduce relies on transpose. There are calls to `ttnn::transpose` in ttnn/cpp/ttnn/operations/reduction/generic/generic_reductions.cpp

**Comment by sjameelTT** [comment]
I see, are dimensions currently mismatching or is pcc bad in reduce? I'm curious because the user of `ttnn::transpose` on main right now should not see any unnecessary padding at the moment. Unless there's a bug, they should see the correct shape on the output, and shouldn't need to do any processing on the input.

input shape for transpose_hc:
`[N, C, H[H_padded], W[W_padded]]
`
output:
`[N, H, C[C_padded], W[W_padded]]`

If this isn't true then that's a bug.

**Comment by sjameelTT** [comment]
I think that's because the input N is padded, which we don't expect in transpose. That should be fixed independent of this change, though I'm curious about the use-case for padded N.

**Comment by bbradelTT** [comment]
Is there an issue where that would be fixed?

It's for a reduce call. I'm hoping most of the padding can go away with the new tensor layout work.

**Comment by bbradelTT** [comment]
> do you have a python test I could use to test this out? I am curious as to how we even get to a tensor with padded N. What is the op call that creates a padded N value?

I don't. I was trying to fix reduce with the inputs provided in https://github.com/tenstorrent/tt-metal/issues/13361#issuecomment-2457913091 but there were too many issues and I postponed the effort until the new tensor layout is far enough along.

**Comment by ntarafdar** [comment]
@sjameelTT is this completed with your merge?
