### ISSUE TITLE
Circular interaction with UMD?

### ISSUE THREAD

**Issue by blozano-tt** [tenstorrent/tt-metal#14449]
We use ARCH_NAME to select the correct host_mem_address_map.hpp FROM UMD!!!!

https://github.com/tenstorrent/tt-metal/blob/d4b7fc229bc8379c1f2ecec21908a3e361595ee8/tt_metal/llrt/tt_cluster.hpp#L14

Select 2 params to put them in a struct
https://github.com/tenstorrent/tt-metal/blob/d4b7fc229bc8379c1f2ecec21908a3e361595ee8/tt_metal/llrt/tt_cluster.hpp#L316-L317

And give it back to UMD:
https://github.com/tenstorrent/tt-metal/blob/1186a849ec538c2e09251157864335af1de4f109/tt_metal/llrt/tt_cluster.cpp#L307

This seems circular.

UMD can detect the ARCH, and select the right params.

**Comment by abhullar-tt** [comment]
This makes sense to me, I don't think these have ever changed

**Comment by broskoTT** [comment]
Same goes for at least some parts of 
set_device_l1_address_params
set_device_dram_address_params
set_driver_eth_interface_params

This is planned as part of https://github.com/tenstorrent/tt-umd/issues/106
The idea is to move all the hardware specific arguments inside UMD. If something can't be changed freely by the user, or the user is not expected to know or modify it, it should probably be moved inside UMD.

You can probably close this issue, since the change will probably start from the UMD side, and we'll track it by referenced issue.
