### ISSUE TITLE
Llama70b trace demo hangs after several decode iterations

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#15018]
On main (a5d9979), the [llama70b demo](https://github.com/tenstorrent/tt-metal/tree/main/models/demos/t3000/llama3_70b) is hanging (with trace) after several decode iterations. The last known working commit was 81033ff. The hang also occurs when running with 10 layers (instead of the full 80), but has not been observed when running with 1 layer.

Command:
```
WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml pytest -svv models/demos/t3000/llama3_70b/demo/demo.py::test_LlamaModel_demo[wormhole_b0-True-device_params0-short_context-check_disabled-sampling-tt-70b-T3000-10L-decode_only-trace_mode_on-text_completion-llama3]
```

cc @cglagovichTT @uaydonat

**Comment by skhorasganiTT** [comment]
The hang starts occurring with commit d9df440. @jbaumanTT Would you be able to take a look?

**Comment by skhorasganiTT** [comment]
The hang also occurs non-deterministically when running the demo without tracing (by replacing `trace_mode_on` with `trace_mode_off` in the command above).

**Comment by jbaumanTT** [comment]
@pgkeller FYI the async ringbuffer patch caused this problem for some reason. I'm currently investigating.

**Comment by jbaumanTT** [comment]
Had to run with export TT_METAL_WATCHER_DISABLE_NOC_SANITIZE=1 for the hang to happen with the watcher enabled, but I'm seeing this error then:


```
                 Always | WARNING  | Watcher detected stack usage within 10% of max on Device 0 Core (x=1,y=1): trisc0! Kernel ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/kernels/compute/sdpa_flash_decode.cpp uses 292/320 of the stack.
                 Always | FATAL    | Watcher detected stack overflow on Device 0 Core (x=1,y=1): trisc1! Kernel ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/kernels/compute/sdpa_flash_decode.cpp uses 256/256 of the stack.
```

**Comment by pgkeller** [comment]
> Had to run with export TT_METAL_WATCHER_DISABLE_NOC_SANITIZE=1 for the hang to happen with the watcher enabled, but I'm seeing this error then:
> 
> ```
>                  Always | WARNING  | Watcher detected stack usage within 10% of max on Device 0 Core (x=1,y=1): trisc0! Kernel ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/kernels/compute/sdpa_flash_decode.cpp uses 292/320 of the stack.
>                  Always | FATAL    | Watcher detected stack overflow on Device 0 Core (x=1,y=1): trisc1! Kernel ttnn/cpp/ttnn/operations/transformer/sdpa_decode/device/kernels/compute/sdpa_flash_decode.cpp uses 256/256 of the stack.
> ```

stack overflow could be a sign of a problem as it means the stack may over-write the globals, however, if there are few globals stack overflow could be benign.  you can tweak the stack size in dev_mem_map and see if the stack overflow goes away or if the kernel fails to compile (since a larger stack reduces space for globals).

**Comment by jbaumanTT** [comment]
Yeah, I bumped up the stack space and that fixed the warning, but the hang still occurs (I filed https://github.com/tenstorrent/tt-metal/issues/15066 for the stack overflow problem). I'm currently trying to figure out if I can dump state for devices other than device 0. Since I only see device 0 hanging in all_gather, it's likely some other device is hanging and not meeting up at the right time.

**Comment by tt-asaigal** [comment]
Some observations on my end:

- The hang almost always consists of at least some chips running an all-gather.
- At the time of the hang, a subset of devices has made it to the all-gather op, while at least a single chip is hung 2 ops before the CCL (I found that the chip local op that hung was usually after a DRAM Sharded MM).
- For some chips executing the hanging all-gather, EDM cores are either hung during kernel execution (this is expected). On others, the EDM cores are waiting for a `go_signal` from `dispatch_s` to begin execution. Logging on `dispatch_s`  shows that the `go_signal` has been sent to the EDM cores over NOC (a writer barrier here does not hang, which means that from the `dispatch_s` perspective, the signal was committed to ERISC L1). **This is unexpected behaviour on NOC1**
- For the chip that hung before it got to an all-gather, `dispatch_d` is stalled on a NOC barrier (or waiting for space in a NOC cmd buf), `dispatch_s` is stalled waiting for a notification from `dispatch_d` and workers are waiting for a `go_signal` from `dispatch_s`. **`dispatch_d` being stalled on the NOC is is unexpected behaviour**.
- Inserting a write-barrier inside `matmul/device/kernels/dataflow/reader_bmm_tile_layout_in0_sender_dram_sharded.cpp` causes model compile and unit tests to hang consistently. This indicates that NCRISC is incorrectly accessing the NOC when running this kernel, or there is some other latent bug causing the barrier to hang.

Based on the last point, it seems likely that this hang may be directly caused by the DRAM sharded reader kernel, which may be hanging the NOC. I think that this should be debugged as a first step, before we look further into issues with dispatch.

Issue filed here: https://github.com/tenstorrent/tt-metal/issues/15279
fyi @yugaoTT

**Comment by yugaoTT** [comment]
pushed a change to yugao/hang. with barrier it can pass now because the number of dest set in mcast matches the actual num cores sent.
The reason is that when receiving responses from noc, I purposely set the number of cores to be less than the actual num dest (was under the impression that this could save some cycle).
Fixing this does not solve hang, as this shouldn't affect the following ops (the sw counter for noc is reset for each op).

**Comment by jbaumanTT** [comment]
We're currently blocked on investigating this until #15279 is fixed. Without that fixed, we can't verify that the NOC hang isn't caused by the op. At the moment the hang seems to be correlated with this exact set of ops that are run, so we want to be able to rule that out.

**Comment by yugaoTT** [comment]
@jbaumanTT the fix to MM op is merged, please let me know if there's further problems, thanks

**Comment by uaydonat** [comment]
Is this fixed?

**Comment by jbaumanTT** [comment]
The async dispatch change was reverted, so you shouldn't see this hang anymore. However, we want to reland that change eventually, so we're still getting to the bottom of why the hang happens.
