### ISSUE TITLE
Model changes by contractors are stalled.

### ISSUE THREAD

**Issue by jvasilje** [tenstorrent/tt-metal#15020]
MCW can't merge a bunch of PRs. The list of reviewers is large, and it even includes folks from the Moreh team, which is extremely inefficient. 

As first step, I'd like the list of reviewers to be reduced - something is very wrong with the current flow. It's either our folder structure, of code reviewers structure. 

Some data:

**List of models that are blocked (look at column G)** 
https://docs.google.com/spreadsheets/d/1Dx0QixtRB4_JZ6psOX6q4LNaW40-p8zJ_XTWK2Ootdg/edit?gid=1795313225#gid=1795313225

**An example issue:**
https://github.com/tenstorrent/tt-metal/pull/13475/files

**Comment by bkeith-TT** [comment]
Actions:
- Determine current 'average' time to code review
- Determine best practice time to code review
- Brainstorm solutions
- Implement solutions

**Comment by jvasilje** [comment]
fyi @zzigler-tt @boris-drazic 

Let's work on this with some expediency. To help, here is a list of Pending PRs from MCW
https://docs.google.com/spreadsheets/d/1Dx0QixtRB4_JZ6psOX6q4LNaW40-p8zJ_XTWK2Ootdg/edit?gid=470056989#gid=470056989

When I look at these PRs, I see the following dates:
Oct 3
Jun 11
Sep 13
Oct 4
May 9
...

Here's an example PR with 19 reviewers. 
https://github.com/tenstorrent/tt-metal/pull/8339

I'd like us to review the folders and code owners as a first pass. 
First round of issues, as I see it:
- too many reviewers
- Moreh is triggered to review model demo changes. This makes zero sense to me.

**Comment by zzigler-tt** [comment]
Also, are the approvers receiving notifications thats there are PR's pending review? I am trying to understand how we can have these items sitting for such a long time.

**Comment by jvasilje** [comment]
@zzigler-tt even if you get pinged to review/approve a PR, and you see **19 REVIEWERS** listed there, you are likely to do nothing and assume that someone else will handle it.

**Comment by bkeith-TT** [comment]
2024-11-18 update:
Of the 8 PRs in question:
- 2 are now approved and ready
- 4 are waiting on comment from dev (about testing)
- 2 are waiting on code review

**Comment by uaydonat** [comment]
Reviewers are added by default based on CODEOWNERS. 

1. Since all models added a ttnn integration test, they all need approvals from ttnn team. One person should just approve it to ublock these.
2. In addition, MCW also needs an approval from me or Raymond since these are new additions to the /models folder.
Raymond will check if the CI tests are good, will comment if they are. Either me or someone from my team will review the code, then we will give the final approval for each.

**Comment by tt-rkim** [comment]
For Utku's comments

1. I have an issue to move the ttnn integration tests to post-commit. There are some pipeline issues with that, but in progress. @TT-billteng and @afuller-TT have also pointed out that longer-term solutions include doing multiple things such as reorganizing tests so they're closer to the code + reflect more accurately how we think of our testing.
2. I've put up a PR so that contractors can click in one pipeline button all these pipelines they need to run, as they always add a device perf, e2e perf, nightly ttnn integration, and demo tests: https://github.com/tenstorrent/tt-metal/pull/15231

As I mentioned in Slack, we also need to cultural passdowns to encourage contractors and devs to:

- prioritize code review. We are all busy and do important work, but unblocking someone is also important work.
- suggest areas where we can improve documentation so our review and test processes are clear. The READMEs in the models folder could be a good place to put this info.
- raise issues / delays if they perceive them, rather than the current culture of silence, which leads to code becoming stale.

**Comment by bkeith-TT** [comment]
Lower urgency tasks have been collected into: https://github.com/tenstorrent/tt-metal/issues/15446

**Comment by smehtaTT** [comment]
Deprioritize since MCW is unblocked based on progress from @uaydonat  at https://docs.google.com/spreadsheets/d/1Dx0QixtRB4_JZ6psOX6q4LNaW40-p8zJ_XTWK2Ootdg/edit?gid=470056989#gid=470056989
