### ISSUE TITLE
[Bug Report] Cannot reshape on device tiled tensor from (1, 1, 1[32], 1024) to (1, 1, 32,32)

### ISSUE THREAD

**Issue by marty1885** [tenstorrent/tt-metal#15851]
**Describe the bug**
Though not optimal, reshaping 1D vectors into matrices is sometimes needed in GGML for inference. The new reshape code fails to perform such reshape. The following Python code demonstrates the issue

```py
import ttnn
import torch

device = ttnn.open_device(device_id=0)
x = ttnn.from_torch(torch.ones(1024), layout=ttnn.TILE_LAYOUT).to(device)
y = ttnn.reshape(x, (32, 32))
```

With log
```
                  Metal | INFO     | Initializing device 0. Program cache is NOT enabled
                  Metal | INFO     | AI CLK for device 0 is:   1000 MHz
                  Metal | INFO     | MMIO Device 0 : Tunnel 0 : Device 0
                  Metal | INFO     | MMIO Device 0 : Tunnel 0 : Device 4
                 Always | FATAL    | dtype cannot be specified when converting to ROW_MAJOR_LAYOUT!
```

**To Reproduce**
1. Run the above python progeam
2. See error

**Expected behavior**
Reshape should work

**Screenshots**

**Please complete the following environment information:**
- OS: Arch Linux
- commit: 876aff0e5582bc5504f581a5c4ea5780a5f4b1c9

**Additional context**

**Comment by ntarafdar** [comment]
i spoke to @jvegaTT . He is aware of the problem and should be a simple fix he can get to this week.

**Comment by marty1885** [comment]
I see the new GGML tag :)

**Comment by jvegaTT** [comment]
I just verified the above code passes on main as shown below. The referenced commit is 4 days old and there have been multiple changes in reshape since then, it is possible the issue was corrected in one of those
![Image](https://github.com/user-attachments/assets/963e924e-58c0-4807-9b9c-77549e82bcb9)

**Comment by jvegaTT** [comment]
I am closing the issue as it is working on our end, I also tested a reshape from (1,1,1,1024) to (1,1,32,32) directly and added PCC checking it also worked. If however there is still an issue, please reopen and I will investigate.

**Comment by marty1885** [comment]
Weird. I am seeing the issue on yesterday's commit, even a complete rebuild. 
![Image](https://github.com/user-attachments/assets/352ee7a7-6a50-4d35-8a04-161013a0660f)

Update: same symptom on e8465bc101b3e98721bd094309f8448f1800ae6f

**Comment by jvegaTT** [comment]
I am trying to understand how your environment differs from mine. I created this branch https://github.com/tenstorrent/tt-metal/compare/main...refs/heads/jvega/issue_15851 Which differs from main just that I added to the testing plan the above function and one with PCC checking on the shape mentioned and ran it through our testing pipelines just so that it is run on wormhole, blackhole, and grayskull to tick all the boxes. (https://github.com/tenstorrent/tt-metal/actions/runs/12285582415) The post commit with this test added succeeds.
