### ISSUE TITLE
test_uniform.py::test_uniform fails occasionally

### ISSUE THREAD

**Issue by sjameelTT** [tenstorrent/tt-metal#16066]
I noticed this when it failed multiple times on my own change. There is a torch seed, but the ttnn uniform distribution creation is not seeded, so the results change every time. The `rtol=0.5` is fairly high so it ends up passing the majority of times but it's flakey. If you run it several hundred times, even with the same seed it will fail at some point.

To reproduce:

1. Checkout branch: [sjameel/test_uniform_failure](https://github.com/tenstorrent/tt-metal/tree/sjameel/test_uniform_failure) and then build
2. `pytest "tests/ttnn/unit_tests/operations/test_uniform.py::test_uniform[dtype=float32-rand_range=[-5.1, 1.2]-shape=[32, 32]]"`

I printed out the outputs in the test. It changes every time, and generally fails at some point. If it doesn't fail the first try you should be able to rerun it until it does. We likely need to somehow add a seed to the ttnn api here to make the test work.

**Comment by tt-aho** [comment]
I've also seen similar issues with the bernoulli op. Torch is seeded but the ttnn op is not seeded https://github.com/tenstorrent/tt-metal/actions/runs/12014719074/job/33492436738

**Comment by sjameelTT** [comment]
Yeah we need some sort of seed for the ttnn side as well, is this an existing capability for the device.

**Comment by sjameelTT** [comment]
Seems like rand_init has a seed that is always a random value.

**Comment by BuiChiTrung** [comment]
I set the rtol pretty high (0.5) due to the fact that tensix instruction used to generate random `TTI_SFPMOV(0, 9, p_sfpu::LREG0, 8);` is not pseudo-random (which is reported [here](https://github.com/tenstorrent/tt-llk-wh-b0/pull/26#issuecomment-2382729826), followed up [issue](https://github.com/tenstorrent/tt-metal/issues/13904)).

To ensure consistency in the test results, I propose adding a seed parameter to the Uniform and Bernoulli ops. If you guys agree with this workaround, I'll open a PR for implementation.

**Comment by sjameelTT** [comment]
Yes, a seed parameter would be good for consistency. I see there already is a seed set, it's just not exposed at the API and it's always randomly initialized.

**Comment by mrshaw01** [comment]
@sjameelTT Would you ping your team review Trung's PR?

**Comment by sjameelTT** [comment]
I reviewed it, lgtm

**Comment by BuiChiTrung** [comment]
Resolved in this #16179
