### ISSUE TITLE
Tracy profiler support for n300

### ISSUE THREAD

**Issue by mo-tenstorrent** [tenstorrent/tt-metal#3960]

**Comment by aliuTT** [comment]
adding initial support for profiling host for remote device and enabling dumps from ethernet core: https://github.com/tenstorrent-metal/tt-metal/pull/4422

No changes to post process scripts yet.

**Comment by mo-tenstorrent** [comment]
Thanks for the merge Allan. Any points to keep in mind coming from this merge?

**Comment by aliuTT** [comment]
@mo-tenstorrent There was no functional changes to tensix worker profile dumps. I added an equivalent path for profiling on ethernet cores only. I also added device ids to the runtime scope names, so when I'm dumping multichip it's more clear where each call is coming from.

Also, as mentioned earlier, I didn't make any changes to post process scripts for ethernet yet, so this issue is still open

**Comment by mo-tenstorrent** [comment]
Great! ETH cores have access to DRAM as well, right? For this ticket to be fully implemented, ETH cores will need to push their profiling results to DRAM through NOC. Considering they are used as dispatch cores, they should be fine right?

**Comment by aliuTT** [comment]
Yep, eth cores have DRAM access. I don't think I'm pushing profiled results to DRAM from eth core for now.

**Comment by mo-tenstorrent** [comment]
Great, No `main` is all L1 based right now. Migrating to host reading results from DRAM soon.

**Comment by aliuTT** [comment]
Ah got it
