### ISSUE TITLE
No-op sharded writers where possible (packer commits to L1)

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#4444]

**Comment by nsmithtt** [comment]
@mywoodstock, is this issue still relevant?

**Comment by mywoodstock** [comment]
We already have this done for maxpool. But still remains for convs afaik.

**Comment by mywoodstock** [comment]
@shwetankTT seems like this is all good, you can leave in the `cb_wait_front`s as is for `SHARDED_OUT`.

**Comment by shwetankTT** [comment]
Yeah I tested it. For sharded tensor, the code flow never reaches to noc_async_write.
I added couple of print statement to validate it.

**Comment by davorchap** [comment]
For SHARDED_OUT did we remove the writer kernel altogether ?

It's not used, so just dispatch overhead

**Comment by mywoodstock** [comment]
> For SHARDED_OUT did we remove the writer kernel altogether ?
> 
> It's not used, so just dispatch overhead.
> 
> Removing any unused writer will improved end2end perf
> 
> Looping in @tt-aho

Yes, we don't have any writer kernels anymore.

**Comment by TT-BrianLiu** [comment]
We use the "writer" kernel to read in weights and activcations (for the 1D split reader case)

**Comment by mywoodstock** [comment]
> We use the "writer" kernel to read in weights and activcations (for the 1D split reader case)

Yes, so technically it is a reader kernel. We dont have actual writer kernels anymore.

**Comment by tt-aho** [comment]
> For SHARDED_OUT did we remove the writer kernel altogether ?
> 
> It's not used, so just dispatch overhead.
> 
> Removing any unused writer will improved end2end perf
> 
> Looping in @tt-aho

@davorchap even if we have unused writer riscs, if we don't load kernels on them but still have other kernels on the riscs on the same core, wouldn't that add additional overhead since these become separate kernel groups (one with other kernels + writer, and one with just other kernels) so they end up being separate transactions for various fd2 cmds? We haven't really done profiling for this use case/optimization but wouldn't it be better to use the rt arg disable method instead?
