### ISSUE TITLE
tt_lib logical operations - Low PCC when one of the operands is BFLOAT_8B [Grayskull and Wormhole]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#4673]
Logical eltwise operations `tt_lib.tensor.logical_and`,`tt_lib.tensor.logical_or` operations fail with low PCC in  some combinations on both GS and WH cards when there is at least one bfloat8 operand

**To Reproduce**
Checkout `main` branch. Run unit tests 

`tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_and.py`  
`tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_or.py`  

```
1. pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_and.py
2. pytest tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_or.py
```

**Expected behavior**
There is at least one test cases per unit test expected to fail with low PCC error.

For example, one of the tests is expected to fail with this result:
```
 Max ATOL Delta: 1.0, Max RTOL Delta: inf, PCC: 0.0, PCC check failed
```

**Getting Details**
You can get more combinations tested using test sweep: `tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/pytorch_eltwise_logical_or.yaml` 

Result will be saved in `./result-sweeps` folder

**Comment by umadevimcw** [comment]
@npetrovic-tenstorrent We tried debug the above issue and observed the following,

Logic of logical or/and involves checking not equal to zero (its combination of arithmetic and comparison ops)

```
case BinaryOpType::LOGICAL_AND:
            op_name = "mul_tiles";
            op_code = "2";
            defines.merge(eltwise_unary_op_utils::get_defines(UnaryOpType::NEZ, std::nullopt, "0", idst));
            break;
  case BinaryOpType::LOGICAL_OR:
      defines.merge(eltwise_unary_op_utils::get_defines(UnaryOpType::NEZ, std::nullopt, "PRE_IN0_0"));
      defines.merge(eltwise_unary_op_utils::get_defines(UnaryOpType::NEZ, std::nullopt, "PRE_IN1_0"));
      op_name = "add_tiles";
      op_code = "0";
      defines.merge(eltwise_unary_op_utils::get_defines(UnaryOpType::GTZ, std::nullopt, "0", idst));
  
```
The reason for low pcc even though the values are not qual to zero we are getting result as `0` instead of `1`

When we check logic of NEZ it depends on `_sfpu_is_fp16_zero_` function which is not working properly when we give bfloat8 data type hence we need to use bflaot16 for both the type

As function implies I assume this function is specific to bfloat16.

@npetrovic-tenstorrent Please share your comments. I am planning to change the datatype to bfloat16 instead of bfloat 8

**Comment by umadevimcw** [comment]
@npetrovic-tenstorrent In the recent main, the above tests passed in  WHB0 and GS. Hence closing this issue.
