### ISSUE TITLE
GEGLU fails with low pcc with ttnn.linear

### ISSUE THREAD

**Issue by Sudharsan-V** [tenstorrent/tt-metal#4877]
**Describe the bug**
When using ttnn.linear within the geglu submodule of the stable diffusion model, a significant decrease in PCC is observed, oscillating in the range of 0.6 to 0.75.

**To Reproduce**
1. Pick the files from the PR https://github.com/tenstorrent-metal/tt-metal/pull/4869
2. Replace `ttnn.matmul` and `ttnn.add` with `ttnn.linear` in the `def geglu` method (models/experimental/functional_stable_diffusion/tt/ttnn_functional_geglu.py)
3. Run the test file `tests/ttnn/integration_tests/stable_diffusion/test_geglu.py` in the PR https://github.com/tenstorrent-metal/tt-metal/pull/4869

**Expected behavior**
The test file  `tests/ttnn/integration_tests/stable_diffusion/test_geglu.py` has 8 test cases, expecting all the test cases to pass with pcc > 0.99. Currently 5/8 test cases are failing. 

**Additional context**
The pcc of the failing test cases are given in the issue [#4790](https://github.com/tenstorrent-metal/tt-metal/issues/4790)

**Comment by TT-BrianLiu** [comment]
@Sudharsan-V  Is this still an issue? I couldn't reproduce what you are seeing here with what's on `main`. The test that wasn't working is always skipped now. Also, there were a couple of issues in the `geglu` implementation: 
<img width="956" alt="image" src="https://github.com/user-attachments/assets/5bd23335-ec3f-4124-9451-deeff119310d">

You can try replacing `ttnn.matmul` and `ttnn.add` with `ttnn.linear` and see if it works now. If it's still an issue, please provide a working repro. Otherwise, can you close the issue?

**Comment by Sudharsan-V** [comment]
@TT-BrianLiu, the test cases are working fine. So, we can close this issue.
