### ISSUE TITLE
Align page size once in the interleaved addr gen constructor

### ISSUE THREAD

**Issue by DrJessop** [tenstorrent/tt-metal#5131]
Currently, page sizes are not consts in interleaved addr gen, and they are aligned on each gen_addr call. They should be consts, and aligned once in the constructor. This is a temporary solution until #5128 is resolved.

**Comment by davorchap** [comment]
to be reviewed as part of FD2

**Comment by pgkeller** [comment]
@tt-aho I seem to recall you fixing this?  Or is this still pending?

**Comment by tt-aho** [comment]
Still pending. Didn't start as it seemed like I would need to add a constructor to the class, which would require us to go update all the kernel files since we aggregate initialize the members at the moment. I think there is a workaround I can do with implicitly initialized elements with the aligned page size that would avoid this though. Will try it out.

There were discussions about cleaning up our addr gens so didn't want to go through and update all the kernel files if we were planning on changing them again.

**Comment by pgkeller** [comment]
OK, yeah, fine to let this sit while we sort out our API(s)

**Comment by tt-aho** [comment]
This is currently resolved using an implicit initializer to align the page_size once. Better solution when we plan on refactoring the AddrGens is to move to a proper constructor and setter methods
