### ISSUE TITLE
Low PCC failure : backward clamp ops - tt_lib.tensor.clamp_max_bw and tt_lib.tensor.clamp_min_bw [Grayskull][Wormhole]

### ISSUE THREAD

**Issue by npetrovic-tenstorrent** [tenstorrent/tt-metal#5147]
Backward clamp operation variants - clamp_min_bw and clamp_max_bw, when run as sweeps fail with low PCC on both Grayskull  and Wormhole.

**To Reproduce**

Checkout `main` branch. 

**Run the sweeps**
You can get more combinations tested using test sweep: 
`tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_backward_clamp_max.yaml` 
`tests/tt_eager/python_api_testing/sweep_tests/test_configs/ci_sweep_tests/broken_grayskull/pytorch_backward_clamp_min.yaml` 

Result will be saved in `./result-sweeps` folder

**Expected behavior**
All test cases for are expected to fail with low PCC error.

For example, one of the tests for clamp_max is expected to fail with this result:
```
Max ATOL Delta: 100.0, Max RTOL Delta: nan, PCC: 0.7029850409727452, PCC check failed
```

There are unit tests for each for GS:

`tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_clamp_min_bw.py`  
`tests/tt_eager/python_api_testing/non_working_unit_tests/grayskull/test_clamp_max_bw.py`  

For WH:

`tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_clamp_min_bw.py`  
`tests/tt_eager/python_api_testing/non_working_unit_tests/wormhole/test_clamp_max_bw.py`

**Comment by npetrovic-tenstorrent** [comment]
Still exhibit low PCC

**Comment by umadevimcw** [comment]
@npetrovic-tenstorrent Reason for low pcc is due to conversion of given data to bfloat 16. 
While debugging we observed that we are getting low pcc due to following input case,
- input value - 93.8287  and min value is 94.0
- In torch input remain same as `93.827` whereas in TT it is stored as `94.0`
- logic of min is `grad * (input>=min)`
- In this for the above input the comparison fails in torch varies in TT it will return one which then multiplied with grad. 
Hence results in low pcc. 

The given input is updated based on BF16 datatype hence the low pcc. Which is applicable to max as well. 

 @jliangTT @tt-aho @eyonland This is issue doesn't requires any change logic that involved in clamp min and max. 
 Please share ur comments as well

**Comment by umadevimcw** [comment]
@npetrovic-tenstorrent @jliangTT Can I close this issue?

**Comment by jliangTT** [comment]
marking as blocked to review with @eyonland

**Comment by tt-aho** [comment]
Can we not update the torch reference to use bfloat16/same value we are using in tt to avoid this issue?

**Comment by VirdhatchaniKN** [comment]
Hi @npetrovic-tenstorrent , @tt-aho 
`clamp_min_bw` and `clamp_max_bw` op support has been removed.

**Comment by VirdhatchaniKN** [comment]
Closing ticket as op support no longer exist
