### ISSUE TITLE
Reshape Error

### ISSUE THREAD

**Issue by dvartaniansTT** [tenstorrent/tt-metal#5197]
**Describe the bug**
Trying to reshape (3, 224, 224) to (224, 224,3) fails on TTNN while reshaping from (3, 224, 224) to (224, 3, 224) works.

**To Reproduce**
1. Go to [my brnach](https://github.com/tenstorrent-metal/tt-metal/tree/dvartanians/unitTests)
2. from metal root dir run "python tests/ttnn/unit_tests/operations/test_reshape.py"

**Expected behavior**
I understand this can be achieved via permute, might be helpful to generate a more informative error message even if it fails.

**Screenshots**

**Please complete the following environment information:**
- OS: [e.g. Ubuntu 20.04]
- Version of software (eg. commit)

**Additional context**

**Comment by eyonland** [comment]
I would expect a ROW_MAJOR_LAYOUT with bfloat16 to fail when reshaping rying to reshape (3, 224, 224) to (224, 224,3) if you end up with a width that is not even.

**Comment by eyonland** [comment]
Our implementation flips a TILE_LAYOUT to ROW_MAJOR_LAYOUT when we have a padded tensor so that we can correctly do the permute on the intended shape.  The fundamental problem is that the op we currently have cannot operate on padded tensors correctly.   We need a kernel developer to update the permute op to handle this case properly.

**Comment by eyonland** [comment]
The above reshape mentioned by @dvartaniansTT would be possible for a TILE_LAYOUT tensor that has been padded if the op were to account for the padding.    My position on this is that we should prioritize this work and update this in metal at some point.

**Comment by dvartaniansTT** [comment]
@eyonland Thanks for your input. Are there any updates to this? cc: @mbahnasTT 
@jliangTT I assigned this to you now please reassign as you see proper.

**Comment by TT-BrianLiu** [comment]
Reshape calls the fallback and the fallback works fine with shapes like: `(2, 224, 224) to (224, 224,2)` or `(4, 224, 224) to (224, 224,4)`. The error message comes from a 4B alignment restriction for creating buffers on device in `ttmetal`. So for row major layout with dtype `ttnn.bfloat16` or `ttnn.uint16`, we must have a width that is multiples of 2. (Note: For smaller dtypes, row major layout is not possible and for tile layout, our width is always multiples of 32).

**Comment by TT-BrianLiu** [comment]
I will add slightly more descriptive error message in `tt_metal/impl/buffers/buffer.cpp`, but for now, we expect user to pad up the tensor width where it's required.

**Comment by TT-BrianLiu** [comment]
Instead of this message in buffer creation, which is hard to understand:
<img width="1174" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/109366241/fec314aa-3289-4497-8e29-b517ddd013ca">

I raised the checking to validate tensor creation and it's clearer now:
<img width="1486" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/109366241/91155570-6b22-40fd-a304-b3cd1935cd75">
