### ISSUE TITLE
Prefill needed for SSMs

### ISSUE THREAD

**Issue by aguhaTT** [tenstorrent/tt-metal#5428]
Please see [notes](https://docs.google.com/presentation/d/1iRnM6PMCV6tapea6ajABv5Bn7bz64OavUbtGSfUkLKw/edit?usp=sharing) for details.

**Comment by jliangTT** [comment]
@eyonland @tt-aho , are you the right folks? seems like we need to talk about this and figure how to approach it. I will yank you guys from the assignees so we know this one needs some triage. feel free to add yourself back in if you already know the next step and is working on it

**Comment by jliangTT** [comment]
Hey @aguhaTT , i am throwing this into the all gather bucket label: op_cat: all gather though it may be a better queue for it. This might be worth a discussion.

**Comment by SeanNijjar** [comment]
Sorry I missed the original notification because github notifications were being sent to personal mail. Got that sorted.

Yes, this looks like something that falls under my umbrella - I'm handling multichip data-movement related primitives (and I believe) kernels.

@aguhaTT, the following is my approximate roadmap:
1) Bringup basic erisc data-mover engine (used to shuttle data between chips), make it reasonably performant, bidirectional.
  -> This is done on branch but needs a few additions at the API level for cleaner interfacing with worker cores
2) Integrate into ring all-gather functionally (should provide a perf improvement to all-gather)
3) Update all-gather to bidirectionality (simple configuration of the erisc data-mover)

At that point I think it'll make sense to evaluate priorities:
- Should I bringup new ops like this one or should I continue optimizing allgather (go to 2D mesh allgather). I'm hoping to hit 3 sometime next week. 

I think we can setup a regular, short discussion so we're up to date on priorities.

**Comment by SeanNijjar** [comment]
Related features/issues:

- [ ] #5563
- [ ] https://github.com/tenstorrent-metal/tt-metal/labels/op_cat%3A%20all%20gather

Issue Tasks (for priority items to consider in the above issues/boards:
- [ ] Identify initial test configurations
  - shapes, input/output layout/allocation, data-type, etc.
- [ ] Identify which models this technique is applicable to and being attempted on

**Comment by jliangTT** [comment]
Hey Sean, assigining you to this. Let me know if this doesn't reflect the reality.

**Comment by SeanNijjar** [comment]
After discussion yesterday, we decided @apalaguha will analyze mamba prefill further and then we'll figure out a development plan. From my end, this is currently lower priority than other tasks as the prefill support here will be needed later than functional bringup of other models.

**Comment by aguhaTT** [comment]
Yes I will publish updated slides today and set a meeting to discuss.

**Comment by jliangTT** [comment]
There was an offline discussion about this. Summarizing here: 

- latest study shows that the need is for data movement kernel (likely without device-to-device communication)
- Sean has done some study on this as part of his all-gather work and has identified shared infra possibly useful even for single chip
- the next step should be triage to the TM op cat and find an assigned owner (will remove the all-gather label for now).


Let me know if i miss anything @SeanNijjar @aguhaTT @uaydonat

**Comment by SeanNijjar** [comment]
Removing myself as assignee since we determined this isn't a CCL op/

**Comment by jliangTT** [comment]
@tarafdarTT , @yan-zaretskiy , we are upgrading this issue as Mamba team has identified this to be a major performance win opportunity. Due to the velocity of executing for javelin, we ask the team to specific highlight the highest ROI performance issue and flag it as P0. Can you start taking scoping this out and take actions?

**Comment by davorchap** [comment]
@tarafdarTT please sync with @aguhaTT and @yan-zaretskiy on the scope of this work

**Comment by yan-zaretskiy** [comment]
I'm working on the issue full-time. I understand the requirements and the scope of this task. It's pretty involved from the algorithm involved point of view, so my conservative ETA is 1 week.

**Comment by jliangTT** [comment]
Thanks @yan-zaretskiy. Since we have plan and have scoped this out. Let's downgrade this to P1 so we can reduce some mental stress for the team. Downgrading...

**Comment by yan-zaretskiy** [comment]
OK, here's the deal. The op in question is the _exclusive_ prefix scan of a 2D tensor along the column dimension, with multiplication as the scan operation. Moreover, the scanning direction is bottom-to-top. In other words, for a given input column 

$$ \begin{bmatrix}
   a_1 \\
   a_2 \\
   a_3 \\
   a_4
\end{bmatrix}, $$

the output column should look like

$$ \begin{bmatrix}
   a_2 \cdot a_3 \cdot a_4 \\
   a_3 \cdot a_4 \\
   a_4 \\
   1
\end{bmatrix}. $$

This transformation has to happen for every column of sharded tilized tensor. The columns are split across cores, so the core below has to communicate the value of its top-most row to the core above it - but this part is not a problem.

The problem I am facing is how to perform the scan within a core shard. The shard is subdivided into tiles, so I have to perform the scan on every tile and then communicate the top row of each tile to the next tile above it. There is currently no LLK that performs such operation on a tile. 

As far as I understand, there's no workaround for this operation, because the scan requires multiplying floating point numbers. So even if we didn't care about performance at all, we couldn't do it on a Grayskull device without an LLK op. My initial idea was to untilize each tile and mess with the row values inside RISC-V, but now I realize it won't work.

**Comment by jliangTT** [comment]
yeah this is not trivial. 

Just talk to Davor - he suggests that we get the TM team together to do a high bandwidth chat. Do you mind setting something up when Naif is back - with @tarafdarTT , @davorchap , @TT-BrianLiu , @ttmtrajkovic.

**Comment by ttmtrajkovic** [comment]
@rtawfik01

**Comment by TT-BrianLiu** [comment]
Can we also loop in model writers? I want to review how this op works. I am confused by this slide
<img width="1066" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/109366241/72b5aafb-4b5f-4ae7-aa07-d18dd8fd8ceb">

**Comment by aguhaTT** [comment]
happy to, btw @yan-zaretskiy also understands the op in great detail.

**Comment by yan-zaretskiy** [comment]
We had a discussion today and @TT-BrianLiu suggested to reshape the tiles of each shard to be able to make use of element-wise tile operations instead of writing a new LLK algorithm, here's the sketch of the general idea:

![scan](https://github.com/tenstorrent-metal/tt-metal/assets/10409817/94cb5549-9f5c-43c9-82af-af73ea26511a)

This requires the clever use of `tilize/untilize`.

**Comment by uaydonat** [comment]
@esmalTT do we close this?

**Comment by esmalTT** [comment]
@uaydonat yes, closing since prefill is now on main since 7d0a58d83b6d51ea2f2ecb21743b1171057364c0
