### ISSUE TITLE
[Feature Request] Signed Integer support

### ISSUE THREAD

**Issue by hschoi4448** [tenstorrent/tt-metal#5472]
**Is your feature request related to a problem? Please describe.**

I'm in the process of implementing an op to handle PyTorch Tensor's getitem, but I've noticed that -1 values are coming in for the index in the BERT model. So, I attempted to create the index tensor as a signed integer type, but it seems that TT's DataType doesn't include signed integers.

```C++
enum class DataType {
    BFLOAT16 = 0,
    FLOAT32 = 1,
    UINT32 = 2,
    BFLOAT8_B = 3,
    UINT16 = 4,
};
```

**Describe the solution you'd like**

Can you support signed integer types? Additionally, it would be great if you could support 8-byte integer types if possible.

**Describe alternatives you've considered**

**Additional context**

**Comment by jliangTT** [comment]
@davorchap , a moreh request: which team should look at it first? LLK, runtime?

**Comment by ttmtrajkovic** [comment]
@hschoi4448,

Could you describe the operation of Pytorch Tensor's getitem? How do you plan to use the values that come in as integers?
signed integers are in sign + magnitude form and int32 is something we could support, but I need to know the use case so I can tell whether that's going to work well or no.
Integers are not native tensix hardware formats and math-heavy operations like matmuls will not work well with integers.

Milos

**Comment by hschoi4448** [comment]
> @hschoi4448,
> 
> Could you describe the operation of Pytorch Tensor's getitem? How do you plan to use the values that come in as integers? signed integers are in sign + magnitude form and int32 is something we could support, but I need to know the use case so I can tell whether that's going to work well or no. Integers are not native tensix hardware formats and math-heavy operations like matmuls will not work well with integers.
> 
> Milos

https://numpy.org/doc/stable/user/basics.indexing.html#integer-array-indexing
The link above is for numpy array indexing, but PyTorch tensor also operates similarly to this. 
```Python
x = np.arange(10, 1, -1)
x
array([10,  9,  8,  7,  6,  5,  4,  3,  2])
x[np.array([3, 3, 1, 8])]
array([7, 7, 9, 2])
x[np.array([3, 3, -3, 8])] <--- minus index here
array([7, 7, 4, 2])
```

As seen in the Python example, the index array can contain negative values.


It seems that the kernel will require below operations
1. addition
2. comparison operations

The comparison operation will be used to check whether the value is too large or too small.
If the value is negative but within the correct range, an addition operation will be performed to make it positive. 
After that, as unsigned values will be used.

 For example, if there is a tensor of size N and the index value is -1, it will be used by adding N to the index to retrieve the last value of the tensor.

**Comment by ttmtrajkovic** [comment]
Thanks.Is this needed to bring up training or for generality of ops?Keep in mind that operations on indices are possible in hardware but working on individual indices one by one is going to be slow and I don’t believe we’ve done tensor manipulation on negative indices before. Sometimes, it’s possible to perform pre-processing on tensors on host before sending them to device (for example, get rid of negative indices on host, rather than checking range and adding N on device). This is always doable effectively if the tensor is a graph input or output.MilosOn Feb 26, 2024, at 23:36, 최형석 ***@***.***> wrote:﻿

@hschoi4448,
Could you describe the operation of Pytorch Tensor's getitem? How do you plan to use the values that come in as integers? signed integers are in sign + magnitude form and int32 is something we could support, but I need to know the use case so I can tell whether that's going to work well or no. Integers are not native tensix hardware formats and math-heavy operations like matmuls will not work well with integers.
Milos

https://numpy.org/doc/stable/user/basics.indexing.html#integer-array-indexing
The link above is for numpy array indexing, but PyTorch tensor also operates similarly to this.
x = np.arange(10, 1, -1)
x
array([10,  9,  8,  7,  6,  5,  4,  3,  2])
x[np.array([3, 3, 1, 8])]
array([7, 7, 9, 2])
x[np.array([3, 3, -3, 8])] <--- minus index here
array([7, 7, 4, 2])
As seen in the Python example, the index array can contain negative values.
It seems that the kernel will require below operations

addition
comparison operations

The comparison operation will be used to check whether the value is too large or too small.
If the value is negative but within the correct range, an addition operation will be performed to make it positive.
After that, as unsigned values will be used.
For example, if there is a tensor of size N and the index value is -1, it will be used by adding N to the index to retrieve the last value of the tensor.

**Comment by razorback3** [comment]
> Thanks.Is this needed to bring up training or for generality of ops?Keep in mind that operations on indices are possible in hardware but working on individual indices one by one is going to be slow and I don’t believe we’ve done tensor manipulation on negative indices before. Sometimes, it’s possible to perform pre-processing on tensors on host before sending them to device (for example, get rid of negative indices on host, rather than checking range and adding N on device). This is always doable effectively if the tensor is a graph input or output.

Thanks to Milos for your kind reply.

First of all, it is for training workload.
Second, yes, I agree that working on individual indices one by one in the data movement kernel can be slow and it is preferred to pre-process in CPU.

Nevertheless, this is a required feature for us because:
1. Some tensors can be already on the device and can cause more overhead to read from the host, pre-process, and then put back on the device.
2. Index tensors given to PyTorch getitem is usually very small. So, it won't cause much overhead to process them in the data movement kernel.

I would reconsider asking for this feature if it is hard to support or takes a lot of time to support it.
However, I guess that it is not time-consuming work to add because, as you said, the hardware is already there and it does not require any LLK mod but requires just adding one more data type in the eager-level (please correct me if I am wrong).

In addition, it can be a good option for us to choose to process tensors in the NPU or process them in the CPU depending on the size of the tensors.

**Comment by jliangTT** [comment]
In the review: @davorchap clarified that this only needs to be done in the data movement kernel (int32 signed), and **not** in tensix/sfpu/compute engine.

**Comment by ttmtrajkovic** [comment]
Signed integer support has been added to main: https://github.com/tenstorrent-metal/tt-metal/pull/7424

@hschoi4448, please check if this works for you.

**Comment by hschoi4448** [comment]
> Signed integer support has been added to main: #7424
> 
> @hschoi4448, please check if this works for you.

I tested int32 and found an incorrect result. Please fix it.

https://github.com/tenstorrent/tt-metal/issues/7483

**Comment by hschoi4448** [comment]
I created an int32 tensor and verified that its value is being passed to the dmvk kernel. When I checked with DPRINT, the output looks good. @ttmtrajkovic

**Comment by razorback3** [comment]
I think this issue can be closed as completed since supporting int32 in the compute kernel is not what Moreh originally requested.
