### ISSUE TITLE
Support sharding for bcast add op

### ISSUE THREAD

**Issue by tt-nshanker** [tenstorrent/tt-metal#5657]

**Comment by jliangTT** [comment]
Hey @nsmithtt and @tt-nshanker , is this for triaging to the kernel writer who owns Broadcast? If so, we defintely need a lot more information on this? Or is this your personal todO?

**Comment by tt-nshanker** [comment]
@jliangTT I need to put in more details here about what sharding configs need to be supported in broadcast add op. This issue is for SD perf not functionality. I will probably update this issue next week after I have resolved SD functionality issues that I am working on currently. Depending on availability, one of the team members working on SD model perf will pick this work up.

**Comment by shwetankTT** [comment]
@tt-nshanker @AleksKnezevic  what sharding (height/block) we are looking here?

**Comment by shwetankTT** [comment]
@AleksKnezevic Please provide few test case which are required for SD along with sharding and shape requirement.

**Comment by AleksKnezevic** [comment]
The current shapes / shard specs needed are the following:

<google-sheets-html-origin>
in 0 shape | in 0 grid | in 0 shard_spec | layout | in 1 shape
-- | -- | -- | -- | --
(1, 1, 8192, 320) | (8, 5) | [1024, 64] | BLOCK | (2, 1, 1[32], 320]
(1, 1, 2048, 320) | (8, 5) | [256, 64] | BLOCK | (2, 1, 1[32], 320]
(1, 1, 2048, 640) | (8, 5) | [256, 128] | BLOCK | (2, 1, 1[32], 640]
(1, 1, 512, 640) | (8, 5) | [64, 128] | BLOCK | (2, 1, 1[32], 640]
(1, 1, 2048, 1280) | (8, 5) | [256, 160] | BLOCK | (2, 1, 1[32], 1280]
(1, 1, 512, 1280) | (8, 8) | [64, 160] | BLOCK | (2, 1, 1[32], 1280]
(1, 1, 512, 1280) | (8, 8) | [64, 160] | BLOCK | (2, 1, 1[32], 1280]
(1, 1, 128, 1280) | (8, 5) | [128, 32] | WIDTH | (2, 1, 1[32], 1280)



However, the block sharded on 8x5 specs will change due to https://github.com/tenstorrent/tt-metal/issues/7770. 

@tt-nshanker can you please comment on what will be needed here?

**Comment by shwetankTT** [comment]
Thanks

**Comment by shwetankTT** [comment]
Height sharded added and merged in mainline.

**Comment by johanna-rock-tt** [comment]
@AleksKnezevic @shwetankTT there's a [new variant of bcast h sharded](https://github.com/tenstorrent/tt-metal/pull/9822), but it is currently limited to having bs0==bs1 or bs1 == 1. There's a fallback to the old (and slower, see issue for speedup estimtes) bcast for the case in stable diffusion. Just fyi in case bcast is a bottleneck in your model and you'd like to port this optimisation over to your cases too.

**Comment by AleksKnezevic** [comment]
@mywoodstock, FYI.
