### ISSUE TITLE
Add a way to group DPRINTs on device so they come out all at once

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#5945]
Currently the only way to order dprints on between cores is to use RAISE/WAIT, which can stall the program if the print buffer is full. If you don't use these then there's no guarantee of ordering in prints coming out from the device. We could add a way to group dprints from a core so they are all printed at once on the host side.

Per Paul, could have something like this:
`DRPINT_ALL << “this” << ” and ” << “this” << ENDL() << DPRINT_DONE();`

Essentially this entails adding a separate function call for `DPRINT_ALL` and `DPRINT_DONE`, and support for holding partial results server-side.

**Comment by pgkeller** [comment]
naming could be better, maybe DPRINT_BEGIN and DPRINT_DONE

**Comment by tt-dma** [comment]
We can also investigate prepending "{device}:{core}:{risc}" to these print groups, so they can be read while interleaved in the log. Workaround for this for now is using `TT_METAL_DPRINT_ONE_FILE_PER_RISC` to separate things on a per-risc basis

**Comment by pgkeller** [comment]
This is creeping up in priority, assigned Samarth.  Instead of the proposal above, I think we just make it such that:
1) Host buffers data read from the device
2) Host flushes on "\n"
3) Host flushes at end of a dprint line, eg, "DPRINT << abc << xyz;" will print after xyz but will buffer if it just sees abc
