### ISSUE TITLE
Enable program cache by default

### ISSUE THREAD

**Issue by nsmithtt** [tenstorrent/tt-metal#6180]

**Comment by nsmithtt** [comment]
@arakhmati feel free to reassign, it sounded like you did this last time, but I'm not sure who to direct this to.

**Comment by eyonland** [comment]
We decided it was best not to enable this by default for the foreseeable future.  The reason is because when an op is being developed, it is difficult to know whether the op failed because the it did not function properly or whether the the keys for the op are incorrect and therefore  the wrong cached op is returned.

**Comment by nsmithtt** [comment]
@eyonland, perhaps we can enable by default in CI then?  Effectively it means that caching isn't being tested, unet fails to run e2e

**Comment by nsmithtt** [comment]
CI coverage is coming from tests that use the feature.
