### ISSUE TITLE
FD Multiqueue Gtest issue - Nondeterministic test failure on gs

### ISSUE THREAD

**Issue by ttmchiou** [tenstorrent/tt-metal#6281]
https://github.com/tenstorrent-metal/tt-metal/actions/runs/8217831380 shows a failing test in attempt #1 but passes in attempt #2

rerun 
tt-metal/tests/tt_metal/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue/command_queue/test_EnqueueWaitForEvent.cpp
(MultiCommandQueueSingleDeviceFixture, TestEventsReadWriteWithWaitForEventCrossCQs)

Needs possible triage to determine where source of issue is from

**Comment by vtangTT** [comment]
its ND but easily reproducible within 50 iterations of 
`TT_METAL_NUM_HW_CQS=2 ./build/test/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue --gtest_filter=*TestEventsReadWriteWithWaitForEventCrossCQs*`

**Comment by vtangTT** [comment]
This test is ND failing since it was initially written at this commit: 
https://github.com/tenstorrent-metal/tt-metal/commit/4ec8d35b98602b7336fbd95114dbcebbdc3cb113

I was able to repro usually within 100 iterations of:
`TT_METAL_NUM_HW_CQS=2 ./build/test/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue --gtest_filter=*TestEventsReadWriteWithWaitForEventCrossCQs*` 
on a grayskull vm

Failing case:
<img width="935" alt="image" src="https://github.com/tenstorrent-metal/tt-metal/assets/157417475/1aec3131-ef26-446d-ad0f-66191f1e38cc">

@kmabeeTT

**Comment by TT-billteng** [comment]
thanks @vtangTT for the investigation

**Comment by kmabeeTT** [comment]
Ah thanks for flagging (sorry for delay, OOO yesterday)... I had recently (and again just now) run this specific test few hundred times locally, but for whb0 instead of gs, and not observed any mismatches.  Will grab a GS to take a closer look...

**Comment by kmabeeTT** [comment]
I am able to trim test and reproduce this ND race under some specific conditions, and have some observations, will followup shortly.  In the meantime I merged change at https://github.com/tenstorrent-metal/tt-metal/commit/43ae84a8ef36f8777741eab046bbad97848fe135 just now to skip 2 affected test here for GS only (FYI @ttmchiou saw you were considering skipping for all archs)

**Comment by davorchap** [comment]
Marking this as P3, as FD1 will soon be replaced with FD2

**Comment by pgkeller** [comment]
this is an FD1 bug, seems we can close?

**Comment by kmabeeTT** [comment]
Old, closing.
