### ISSUE TITLE
Rework python_env Makefile to use .Phony target

### ISSUE THREAD

**Issue by dimitri-tenstorrent** [tenstorrent/tt-metal#7255]
The Makefile in `tt-metal/python_env` is using `touch $@` instead of using .PHONY targets.

Example of the code:
```
$(PYTHON_ENV)/.installed-dev-editable:
	echo "Installing editable dev version of ttnn package..."
	bash -c "source $(PYTHON_ENV)/bin/activate && pip install -e ttnn"
	touch $@
```
https://github.com/tenstorrent-metal/tt-metal/blob/76d58ac845b83a7d881e60444684870855525b31/tt_metal/python_env/module.mk#L25

cc: @tt-rkim @TT-billteng What is the priority of this refactor if we are moving to cMake?

**Comment by tt-rkim** [comment]
Not very high as a result, however I'm fairly certain we're going to be using some custom commands very similar to what we're doing in Make right now anyway.

I would leave this work as lower priority for now, and if we get around to switching over to CMake, let's take that time as an opportunity to refactor how we generate default python dev env for devs.

**Comment by tt-rkim** [comment]
@TT-billteng It would , which is why I said not very high priority. We can likely close this issue before this becomes annoying, especially once we change our env creation method. I just asked @dimitri-tenstorrent to please make this for documentation.

> [this](https://github.com/tinygrad/tinygrad?tab=readme-ov-file#from-source) way of installing ttnn
sorry a little confused - it just links to tinygrad. They don't have any C++ extensions from what it looks like.

also unfortuntately we don't get editable install currently with `ttnn` if we try to force it into the python package... I think we should pull `tt_eager` into `ttnn` first to make the python packaging easier.

**Comment by TT-billteng** [comment]
re-visit when CMake fully replaces Make
