### ISSUE TITLE
[Bug Report] C++ exception when using two CQs

### ISSUE THREAD

**Issue by razorback3** [tenstorrent/tt-metal#7288]
**Describe the bug**
When I run “unit_tests_fast_dispatch_single_chip_multi_queue”, it says
`Always | FATAL    | This suite must be run with TT_METAL_NUM_HW_CQS=2`

So, I set “TT_METAL_NUM_HW_CQS=2" and then I get
```
Always | FATAL    | No more available dispatch cores on device 0 to assign. Expand dispatch cores specified in core descriptor YAML
unknown file: Failure
C++ exception with description "TT_THROW @ ./tt_metal/impl/dispatch/dispatch_core_manager.hpp:165: tt::exception
info:
No more available dispatch cores on device {} to assign. Expand dispatch cores specified in core descriptor YAML
0
```

**To Reproduce**
1. Set `TT_METAL_NUM_HW_CQS=2`
2. Run `test/tt_metal/unit_tests_fast_dispatch_single_chip_multi_queue` which is in the test set

**Please complete the following environment information:**
- I used WH(n300) machine which Metal team provided via TT cloud system.
- I used `main` branch (commit c4197513cc04adefea2a88f97ce3630eff8885f0)

**Comment by razorback3** [comment]
@jliangTT 
I assigned P0 label because it is blocking our runtime system implementation.

**Comment by jliangTT** [comment]
hey @razorback3 , p0_showstopper has very specific use within the company - i will downgrade to p1 but have taken that you are blocked check in with @kmabeeTT.

**Comment by kmabeeTT** [comment]
Was in meeting just now with @davorchap and @abhullar-tt and asked this question, and the answer is that multi-cq is not supported today on main for Wormhole (N150 or N300) since introduction of "Fast Dispatch 1.3" on March 5th merge ending at 2c7b7c383, only for Grayskull product which remains on "Fast Dispatch 1.0".  Reason being "there are not enough dispatch cores" like the error says.   Davor will follow up, proposal might be to wait until FD2.0 changes are merged (or try on FD2 branch at some point soon), or use Grayskull in short term.

**Comment by jliangTT** [comment]
yes. thanks for the update. We need to discuss this in our sync meeting today.

**Comment by jliangTT** [comment]
The schedule for the integration complete milestone for Moreh is the end of the week. So this feature is urgently needed. @davorchap  to follow up internally

**Comment by kmabeeTT** [comment]
I didn't remember hearing that my multi-CQ events test broke, so I went to try the mentioned suite just now... and good news is that the test suite works on Wormhole N150 today and wasn't broke by the FD1.3 changes, contrary to what I heard and said above, so maybe that is another short term option too (use WH N150 instead of WH N300), in addition to GS.

**Comment by razorback3** [comment]
Unfortunately, we do not have any N150 card 😢.

**Comment by jliangTT** [comment]
i can spin up a VM for you guys as a stop gap. Will that work?

**Comment by jliangTT** [comment]
When we spoke offline, VM for n150 would not work due to the need to have local instance.

**Comment by davorchap** [comment]
@kmabeeTT and @tt-aho fixed this in FD2 
FD2 on main is anyday now, working through the last set of bugs

**Comment by razorback3** [comment]
Adding @namhyeong-kim in a loop.

**Comment by davorchap** [comment]
@razorback3 and @namhyeong-kim , can you re-base and re-run on latest main, this should work now?

**Comment by razorback3** [comment]
Works well for single NPU.
