### ISSUE TITLE
PCC issue for matmul 2d and in falcon40b attention

### ISSUE THREAD

**Issue by johanna-rock-tt** [tenstorrent/tt-metal#7420]
**Describe the bug**
In falcon40b we see an issue with the two attention matmuls (Q*KˆT) and (scores*V) when using a custom program config for sharding.

Obervations:
- Unit test for the op in isolation is fine
- Running the whole model end to end with one layer is fine too
- Running the model with multiple layers (>=12 layers) in the end to end test shows significant drop in PCC, most apparent for the V Cache
- Using interleaved inputs and the default program config has good PCC
- Using interleaved inputs and the custom program config has bad PCC
- Using sharded inputs (that's what we ultimately want) and the custom program config has bad PCC
- We can't run sharded with the default program config

**To Reproduce**
1. Checkout branch `jrock/prefill-perf2@8b1618f8beb4875730af7e27be48457ac806c39e`
2. Run the the falcon40b end to end test
`pytest models/experimental/falcon40b/tests/test_falcon_end_to_end.py::test_FalconCausalLM_end_to_end_with_program_cache[BFLOAT8_B-DRAM-falcon_40b-layers_12-prefill_seq128-8chips]`
3. You'll see bad PCC
```
Output: Max ATOL Delta: 3.618520736694336, Max RTOL Delta: inf, PCC: 0.9980098587307713
K Cache Layer 11: Max ATOL Delta: 1.4973526000976562, Max RTOL Delta: inf, PCC: 0.9921958122243109
V Cache Layer 11: Max ATOL Delta: 0.6698611974716187, Max RTOL Delta: inf, PCC: 0.9474645013210232, PCC check failed
```
4. Go to models/experimental/falcon40b/tt/falcon_attention.py:550 and comment to use the default program config
5. Run the test again
6. You'll see good PCC
Output: Max ATOL Delta: 2.031583309173584, Max RTOL Delta: inf, PCC: 0.9993171126042951
K Cache Layer 11: Max ATOL Delta: 0.9881148338317871, Max RTOL Delta: inf, PCC: 0.9971689880419534
V Cache Layer 11: Max ATOL Delta: 0.43548619747161865, Max RTOL Delta: inf, PCC: 0.9836490293136927

**Comment by johanna-rock-tt** [comment]
fyi @s-jovic

**Comment by pavlepopovic** [comment]
The issue is that we're using LoFi for the 1D config, and HiFi4 for the default program config.
Even tho you specify that you're using LoFi fro the default program config (that is how it is done in the code via compute_kernel_config), default program config makes the underlying matmul use HiFi4.
Switching the 1D compute kernel config to use HiFi2/HiFI3/HiFi4 yields better PCC then the default one (since packer_l1_acc and FP32 dest accumulation are turned on as well). PCC of the V cache in that case becomes `0.9884457046`
