### ISSUE TITLE
`test_mistral_decoder_inference` non-deterministically hangs on WH

### ISSUE THREAD

**Issue by tt-rkim** [tenstorrent/tt-metal#7678]
https://github.com/tenstorrent/tt-metal/actions/runs/8756382689/job/24033724110

cc: @jliangTT @tt-dma @mtairum @yieldthought

**Comment by tt-rkim** [comment]
Unsure what's happening here... logs aren't helpful either.

**Comment by tt-rkim** [comment]
We may have to stress test locally and see how long it takes before it starts hanging.

**Comment by mtairum** [comment]
Tried a small fix for a different hang we we're seeing `f231adf0cd0825bf11778ee4b6eba97290cc0d15`.

No luck. Run 30 iterations of the `test_mistral_decoder` test, but it seems to hang on the 4th iteration: https://github.com/tenstorrent/tt-metal/actions/runs/8786897181/job/24111186564

One thing to note though. 
We're running this test with eth fast dispatch: `WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml`, similar to the full model test in the perf pipeline. The full model runs 32 decoder layers instead of a single one in this test, so it should also display the hanging behaviour. I wonder if it's due to CI device differences, between the perf pipeline and the nightly fast.

**Comment by tt-rkim** [comment]
The CI machine is a much larger bare metal machine, with over 200GB of RAM.

The nightly machines are much smaller virtual machines with smaller CPUs and 48GB RAM.

However, device wise, there is no differences.

Have you tried running it many times in a loop locally?

**Comment by mtairum** [comment]
> Have you tried running it many times in a loop locally?

Yes, on two different machines. No hangs.

**Comment by tt-rkim** [comment]
What's the status of this? Sorry for the delay
would you like to try on a cloud VM?

**Comment by mtairum** [comment]
Still seeing the hang when I tried yesterday on the latest main. How can I try on a cloud VM?

**Comment by uaydonat** [comment]
@mtairum we should try this with FD2 on latest main to see if the hang is gone.

**Comment by mtairum** [comment]
On latest main this is now passing. Tested 30 runs of the mistral_decode test without any hangs. I'll clean the branch and add PR.

Stress test pipeline passing here: https://github.com/tenstorrent/tt-metal/actions/runs/9004403045/job/24737844802

**Comment by tt-rkim** [comment]
@mtairum Great!

**Comment by tt-rkim** [comment]
@mtairum Please close this once you are merged ?

**Comment by mtairum** [comment]
Fix now merged: https://github.com/tenstorrent/tt-metal/pull/8263
