### ISSUE TITLE
CommonFixture.MatmulLargeBlock incorrect output on multichip, N300

### ISSUE THREAD

**Issue by tt-dma** [tenstorrent/tt-metal#7912]
- Re-enable test (grep for tag #7912)
- `WH_ARCH_YAML=wormhole_b0_80_arch_eth_dispatch.yaml ./build/test/tt_metal/unit_tests_fast_dispatch --gtest_filter=CommonFixture.MatmulLargeBlock`
- Result is bad output from test, see: https://github.com/tenstorrent/tt-metal/actions/runs/8856069066/job/24322007219

**Comment by pgkeller** [comment]
@tt-dma run eth and non eth on same machine, see if hangs are consistent

**Comment by tt-dma** [comment]
Confirmed that this test passes with FD-on-tensix, and fails on FD-on-eth. Nore that this test doesn't hang, just has incorrect output.

**Comment by ubcheema** [comment]
what is the command line to run for multichip?

**Comment by ubcheema** [comment]
There is a bug in cq_dispatcher that misses sending some bytes at end of page when wrapping to the top of cb buffer.
This is causing the mismatch in large matmul when reading back with ERB. The reason we don’t see it in Tensix dispatch is that tensix buffer is large enough that we do not wrap. On Ethernet, we have to wrap and that exposes the issue.
I have tried a hack, that gets the large matmul to pass with ethernet dispatch.
@pgkeller will have to see what a proper fix should be. It's to do with extra accounting we do in `relay_to_next_cb` in `cq_dispatch.cpp`. When packetizing, we count 16 bytes of packet header that has to be added to dispatch payload. This means that of the 4KB dispatch page, we only send 4080 bytes, since 16 are taken by packet header. Later on if we need to wrap, there are still 16 bytes payload remaining in current page. But dispatcher does not send those. It rewinds to start of dispatch cb buffer and ultimately ends up sending 16 garbage trailing bytes in the very last page/transfer. (edited) 

After my hack to get to get the test to pass, there was another bug in host code where I was not setting the buffer size correctly for prefetch_h->Mux. The size depends on dispatch type (Tensix Vs Eth). But the code was always setting the buffer size to be 256 KB which is the total size of eth L1. For tests sending enough prefetcher traffic to cause it to wrap, it would wrap eth L1 and overwrite eth fw and cause it to crash resulting in tests hang.

I will push a fix for mux buffer sizing. I’ll try my hack for dispatch_d on ci and see how it goes.

The branch is here: [ucheema/issue-7912-debug](https://github.com/tenstorrent/tt-metal/tree/ucheema/issue-7912-debug)

**Comment by ubcheema** [comment]
Fixes pushed to fd-2/main.

CommonFixture.MatmulLargeBlock re-enabled for multi chip.
