### ISSUE TITLE
FD2 read bandwidth improvement list

### ISSUE THREAD

**Issue by pgkeller** [tenstorrent/tt-metal#8098]
Use:
  ./build/test/tt_metal/perf_microbenchmark/3_pcie_transfer/test_rw_buffer --page-size 4096 --transfer-size 536346624 --skip-write --num-tests 6
~6GB/s for FD1
~2.5GB/s for FD2
The read numbers are very noisy, more noisy on FD2

A quick look showed the following:
 - Dispatcher writes of prefetch sync use PACKED_WRITE command, should use WRITE_LINEAR
 - Read buffer does two fetch_q writes, I suspect this could be 1.  I think this is for the read and event. That’s 6.5usecs
 - Constructing the commands does mallocs/pushbacks
 - Back to back reads do back to back stalls, could note prior command and only stall when needed
 - Here’s the fun one: adding a delay in the dispatcher by counting to 2000 for every write ~doubles performance, enabling DPRINTS at that point has no effect
I suspect the last one indicates that we should use streaming loads on the host

**Comment by tt-aho** [comment]
One super obvious thing that could give us gains is that for readback, we copy from hugepage -> temp buffer, then temp buffer -> actual buffer.

This was done so we clear the hp as fast as possible, since when writing to the actual buffer we sometimes need additional processing/calculations of pages but since we are clearly host bound, we could try removing the copy to temp and copy from hugepage directly to buffer.

**Comment by tt-aho** [comment]
On this branch `aho/fd2-perf`, after removing the temporary buffer, I see this test go from ~2-2.5GB/s -> ~8.75GB/s on my GS BM.

Running post commit to make sure it's real and I didn't break anything 🙃

**Comment by pgkeller** [comment]
Fantastic!

**Comment by pgkeller** [comment]
w/ Austin's fix FD2 perf beats FD1 but the todo list is still non-trivial.  Changed the title to reflect this is still a todo but no longer losing to FD1

**Comment by pgkeller** [comment]
closing this as most of the issues listed are stale, when we pick up read bw improvements again we should start w/ an analysis from scratch
