### ISSUE TITLE
Expose half tile config in LLK (WH)

### ISSUE THREAD

**Issue by mywoodstock** [tenstorrent/tt-metal#8122]

**Comment by mywoodstock** [comment]
fyi: @davorchap

**Comment by yugaoTT** [comment]
We will use half tile for shading weights in DRAM. The reason is that they're 12 banks and it's sometimes not divisible for the mammal weights. For example, for a weight tensor of 8192x1280. we shard 1280 by 12 banks. if use half tile, each bank can have 112 as width, together we have 112x12=1344. This requires much less padding than the full tile one, which needs to pad to 1536.

**Comment by rtawfik01** [comment]
@yugaoTT can this issue be closed since you merged `16x32` and `32x16`?

**Comment by yugaoTT** [comment]
@rtawfik01 yeah I will close this one
