### ISSUE TITLE
support 1D tensors in ttnn

### ISSUE THREAD

**Issue by davorchap** [tenstorrent/tt-metal#8541]
User should be able to specify a 1D tensor shape , such as `(10)` , today it has to be specified as 2D `(1,10)`

**Comment by arakhmati** [comment]
We support 1D row-major tensors. Tilized tensors have to be 2D

**Comment by davorchap** [comment]
> We support 1D row-major tensors. Tilized tensors have to be 2D

Thanks @arakhmati

Perhaps the original shape after tilizing+padding would still be 1D?
We change the layout but the original would still be 1D

@razorback3 fyi

**Comment by razorback3** [comment]
What our suggestion is:
1D row-major tensor after _padding_ and _tilizing_ -> 2D tensor
But, if we call _shape_without_padding()_ it returns 1D tensor

**Comment by blueblud7** [comment]
@davorchap Would you please share any update regarding @razorback3's comment?

**Comment by davorchap** [comment]
> @davorchap Would you please share any update regarding @razorback3's comment?

Yes, 1D original tensor shape will be preserved.

@nsmithtt ,  @arakhmati and team are working through a proposal to uplift the Tensor class to support this cleanly

**Comment by ayerofieiev-tt** [comment]
@arakhmati @eyonland @yan-zaretskiy for vis for Tensor layout conversation

**Comment by arakhmati** [comment]
We can't change the dimensionality of the shape when calling `shape_without_padding` because it will be misleading in many other cases. And it really doesn't make sense to get tilized tensor's shape as 1D. I think Moreh should add a free function that does what's required and use it in appropriate places. This can't be a part of our infra as of right now
