### ISSUE TITLE
Matmul [(32, 4096) x (4096, 64)] hangs when input is width-sharded

### ISSUE THREAD

**Issue by sraizada-tt** [tenstorrent/tt-metal#8641]
Unit test:
```
def test_sharded_matmul(device):
    input_i_1SBH = ttnn.from_torch(torch.randn(1, 1, 32, 4096), dtype=ttnn.bfloat8_b, layout=ttnn.TILE_LAYOUT, device=device)
    input_i_1SBH = ttnn.to_memory_config(input_i_1SBH, ttnn.create_sharded_memory_config(
            shape=(32, int(4096 / 32)),
            core_grid=ttnn.CoreGrid(y=4, x=8),
            strategy=ttnn.ShardStrategy.WIDTH,
            orientation=ttnn.ShardOrientation.ROW_MAJOR,
            use_height_and_width_as_shard_shape=True,
    ))

    gates_HE = ttnn.from_torch(torch.randn(1, 1, 4096, 64), dtype=ttnn.bfloat8_b, layout=ttnn.TILE_LAYOUT, device=device)
    gate_logits_1SBE = ttnn.experimental.operations.primary.matmul(input_i_1SBH, gates_HE) 

    print("done", gate_logits_1SBE)
    assert True
```

**Comment by TT-BrianLiu** [comment]
You are not passing in any program config to primary matmul. Typically, when you use this matmul, we expect user to specify the exact matmul they are using (in this case, it should be `MatmulMultiCoreReuseMultiCast1DProgramConfig`). If you don't, it currently defaults to `MatmulDefaultProgramConfig` which has less stringent checks for sharding right now. That's why it's probably hanging for you.

Also, the shapes you have here probably won't work for `MatmulMultiCoreReuseMultiCast1DProgramConfig` since we expect the output width to fit on same number of cores as in0 width, which is not possible in this case. This will be fixed this week.

**Comment by bbradelTT** [comment]
It'd be good to
1. [short term] provide a specific program config to get this issue unblocked
2. [long term] incorporate the tensor shapes into a test that will be used to ensure that down the road code that automatically generate a program config works properly with this set up

**Comment by sraizada-tt** [comment]
works with:
```
ttnn.experimental.operations.primary.MatmulMultiCoreReuseMultiCast1DProgramConfig(
            compute_with_storage_grid_size=(8, 4),
            in0_block_w=4,
            out_subblock_h=1,
            out_subblock_w=1,
            per_core_M=1,
            per_core_N=1,
            fuse_batch=True,
            fused_activation=None,
            mcast_in0=True,
        )
```
It works even when program config is not specified. 
Thank you!

**Comment by TT-BrianLiu** [comment]
That's amazing to hear!

**Comment by TT-BrianLiu** [comment]
When you don't specify a program config, which matmul does it run?

**Comment by bbradelTT** [comment]
> When you don't specify a program config, which matmul does it run?

@sraizada-tt the easiest way to find that out is to turn on debug output and copy and paste what it says for the op:
```
                     Op | DEBUG    | Launching Operation: "tt::operations::primary::Matmul" (device<Tensors>)
                     Op | DEBUG    | Attributes:
                     Op | DEBUG    | 	program_config = ...
```
