### ISSUE TITLE
make clean should remove built directory

### ISSUE THREAD

**Issue by uaydonat** [tenstorrent/tt-metal#9137]
if new kernel changes are pulled, program cache should be cleared.

the safest option is to delete the built directory with "make clean", or more advanced option is to rebuild the kernel cache when git hash changes.

fyi @skhorasganiTT

**Comment by aliuTT** [comment]
Rebuilding kernel cache based on hash changes doesn't cover all bases. You could be adding a new kernel and not realize that it's never getting rebuilt. Probably best to must add it to the cmake clean.

**Comment by aliuTT** [comment]
@vtangTT Can we add this to the cmake build flow?

**Comment by vtangTT** [comment]
I can add a custom target like `ninja clean-built` that will clean the `built` folder. In this case, it won't be part of the general clean step and `ninja clean` won't clean it, or do you want it to just be included in the clean step.

@tt-rkim looping you in, not sure if you have any opinions

**Comment by uaydonat** [comment]
Is there a reason you do not want this in `ninja clean`? I think it is safer to add it to there since after I run this expect my repo to be ready.

**Comment by tt-rkim** [comment]
@uaydonat 
We've discussed this before, but I'm hesitant to put this part of `clean` because CMake is purely for build artifacts.

`built` is a runtime artifact.

What we did before is have a `nuke` option that got rid EVERYTHING - build, runtime, environment. In CMake parlance

So given the above, what @vtangTT originally did would actually be my recommendation. And it's what we did before.

Furthermore, the Devil's Advocate use case here would be kernel developers who want to clean locally but only delete the host build. Model developers who don't edit the kernels often likely won't see this use case, unless @uaydonat you've already considered this.

I think one of the two options here would be my recommendation:

- Custom target like what @vtangTT suggested, or something like https://discourse.cmake.org/t/ability-to-clean-individual-targets/2980/17 that would create a target like `metal-nuke`. I think this would enable at a high CMake level something like `cmake --build build --target metal-nuke`.
- A convenience script that does the same thing in `scripts/`. @uaydonat since this affects your team the most, one of your members could propose one, or we could make one for you.

Let us know if that makes sense.

**Comment by uaydonat** [comment]
Ok, we can go for `clean-built` for now. Everybody will have to remember to do this after rebase if they are using persistent-cache.

**Comment by tt-rkim** [comment]
We can add notes in the `CONTRIBUTING.md` to do this.

**Comment by vtangTT** [comment]
https://github.com/tenstorrent/tt-metal/pull/9184 merged to main. 

Please try out `ninja clean-built -C <build_folder>`.
