### ISSUE TITLE
Floor and Trunc Blocker

### ISSUE THREAD

**Issue by eyonland** [tenstorrent/tt-metal#9394]
Reciprocal is being used and showing inaccurate results and this impacts the Floor and Trunc ops being developed by MCW.
See details on https://github.com/tenstorrent/tt-metal/pull/9098

This issue was originally discovered when building the mod op.   
[MOD issues.pdf](https://github.com/user-attachments/files/15807471/MOD.issues.pdf)
The solution proposed on the mod did some clever math to work around this problem (see:  https://github.com/tenstorrent/tt-metal/pull/9365).

**Comment by rtawfik01** [comment]
For the examples above of recip(1) = 0.9961 and recip(2) = 0.4980, those results are not "wrong" but they are not accurate due to different factors, one of them being its float16b not float32. The other question here is @Aswinmcw @VirdhatchaniKN , was the reciprocal above run in approximate mode? So the flag `APPROXIMATE_MODE`, was it set to true? If that's the case, that's another reason for the inaccuracy.

**Comment by eyonland** [comment]
Per discussions.... the inaccuracy in reciprocal is expected based on dataformats and approx mode, and the MCW team is now just passing in 1/value from host.
