### ISSUE TITLE
Regression in Falcon7b-prefill-128-async t3000 perf test

### ISSUE THREAD

**Issue by skhorasganiTT** [tenstorrent/tt-metal#9422]
There has been a regression in the Falcon7b-prefill-128-async t3000 inference time from 0.09s to 0.1s.

Last passing run: https://github.com/tenstorrent/tt-metal/actions/runs/9465212387
First failing run: https://github.com/tenstorrent/tt-metal/actions/runs/9472989413

**Comment by skhorasganiTT** [comment]
@pavlepopovic @s-jovic would you be able to take a look? The inference times for the other prefill configs seem unaffected.

**Comment by pavlepopovic** [comment]
I'll take a look

**Comment by pavlepopovic** [comment]
I've run the test locally 10 times on latest main on t3006 machine. 9 test runs result in inference time less then 0.09s, 1 took 0.119s, so it seems like some kind of a glitch happens once in a couple of runs.
Also, on latest run on main ( https://github.com/tenstorrent/tt-metal/actions/runs/9508548757 ) , 128-async-prefill took 0.081s (the tests failed due to mixtal seg fault, but prefill succeeded and reported numbers).

**Comment by skhorasganiTT** [comment]
I saw the slower inference time a couple times on different runs, but if we see that the newer runs have better perf again perhaps we can just readjust the target.

**Comment by pavlepopovic** [comment]
Had a theory that machine was not in perf_mode, hence causing this (took inspiration from [this](https://tenstorrent.slack.com/archives/C06JN2KU79D/p1718278425958009) thread). And indeed, t3006 was set to run in 'on demand' mode. Tried switching it to 'performance', and it made no difference, there's still flakiness)
Having an accurate value as expected inference time is welcome, so we know when the test fails it is due to a regression.
Thinking that we should maybe run the inference say 10 times, and report min as the model_inference_time? Hopefully that way it'll be more stable

**Comment by skhorasganiTT** [comment]
Yes, warmup runs is a good idea in general, but I'm not sure if it will help fix this issue as it seemed specific to only this prefill config and not the other ones.
