### ISSUE TITLE
Concat Config Support Needed for YOLOX

### ISSUE THREAD

**Issue by ankitmcw** [tenstorrent/tt-metal#9630]
Concat variant in Head and Focus submodule failing.
1. Head submodule concat:
`ttnn.concat: ([(1, 1, 6400, 4), (1, 1, 6400, 80), (1, 1, 6400, 1)], dim=3)` 
- For TILE_LAYOUT, gives unexpected output shape `ttnn.Shape([1, 1, 6400, 132[160]])`. Expected shape `[1, 1, 6400, 85]`
- For the ROW_MAJOR_LAYOUT test, an error is thrown stating  `Page size must be divisible by sizeof(uint32_t) because buffers hold uint32_t values`

2. Focus submodule concat:
`ttnn.concat: ([(1, 1, 102400, 3), (1, 1, 102400, 3), (1, 1, 102400, 3), (1, 1, 102400, 3)], dim=3)`
- For TILE_LAYOUT, gives unexpected output shape `ttnn.Shape([1, 1, 102400, 99[128]])`. Expected shape `[1, 1, 102400, 12]`
- For the ROW_MAJOR_LAYOUT test, an error is thrown stating  `Page size must be divisible by sizeof(uint32_t) because buffers hold uint32_t values`

To reproduce,
checkout to branch [here](https://github.com/tenstorrent/tt-metal/compare/main...ankit/concat_unittest_yolox)
and run
```
cd $TT_METAL_HOME
pytest tests/ttnn/integration_tests/yolox_m/test_ttnn_concat_focus.py
pytest tests/ttnn/integration_tests/yolox_m/test_ttnn_concat_head.py
```

**Comment by punithsekar** [comment]
Note: The issue is up to date. Even in latest main the same issue occurs.

**Comment by tarafdarTT** [comment]
looking at this now.

**Comment by sjameelTT** [comment]
Supporting concat on Tiled layouts with padding that isn't simply on the last tensor is difficult. I don't think the kernels account for this. For the focus submodule for example the shapes, with padding on the relevant dimension, are as follows:

`[(1, 1, 102400, 3[32]), (1, 1, 102400, 3[32]), (1, 1, 102400, 3[32]), (1, 1, 102400, 3[32])]`

The current implementation assumes the padded shape are the true shapes, and appends them together. It initializes the output shape to the first input_tensor's shape so it records its padding as the only padding (3 padded to 32, for a difference of 29). Thus we get `(1, 1, 102400, (32*4 - 29)[32*4=128])` = `(1, 1, 102400, 99[128])`. I don't think we can trivially add this support inside the kernel.

Bfloat16 row major throws an error because we need all dims aligned to 4 bytes, this one might be easier to fix. As long as one of row major or tiled is supported are you unblocked?

**Comment by sjameelTT** [comment]
Follow up question: is it possible to swap dim=2 and dim=3 and concatenate along dim=2 for each tensor? 

Head submodule:
`ttnn.concat: ([(1, 1, 4, 6400), (1, 1, 80, 6400), (1, 1, 1, 6400)], dim=2)` instead of `ttnn.concat: ([(1, 1, 6400, 4), (1, 1, 6400, 80), (1, 1, 6400, 1)], dim=3)`

Focus submodule:
`ttnn.concat: ([(1, 1, 3, 102400), 1, 1, 3, 102400), 1, 1, 3, 102400), 1, 1, 3, 102400)], dim=2)` instead of `ttnn.concat: ([(1, 1, 102400, 3), (1, 1, 102400, 3), (1, 1, 102400, 3), (1, 1, 102400, 3)], dim=3)`

This works for row major

**Comment by mbahnasTT** [comment]
@saichandax can you check the fixes by revisiting YoloX settings?

**Comment by sjameelTT** [comment]
The changes that got put in will assert out on these inputs rather than give incorrect shapes. We will need kernel-level support if we want native support for these dimensions in tiled format, and some tensor creation stuff for row-major as well.

**Comment by saichandax** [comment]
Sure @sjameelTT , We'll check the fix given for row-major and update this issue.
Thank you.
