### ISSUE TITLE
PCC error for `mul` with sharded input

### ISSUE THREAD

**Issue by yieldthought** [tenstorrent/tt-metal#9773]
Painfully discovered and debugged during Grok-1 bringup. The `mul` operator (and inline `*` operator) do not support sharded inputs. They silently produce bad results for _some_ of the cores. Oh, and their output is interleaved instead of respecting the input memory config and remaining sharded.

Added a unit test for this to `/home/moconnor/main-metal/tests/ttnn/unit_tests/operations/test_mul.py` (`test_multiply_with_scalar_sharded`) which fails on main. Available in branch `yieldthought/mul_sharded_scalar`.

**Comment by TT-BrianLiu** [comment]
The output `memory_config` is forced to interleaved always for scalar `mul` and it's related to this issue: https://github.com/tenstorrent/tt-metal/issues/7637

The default should be the `memory_config` of the input tensor, which is `HEIGHT_SHARDED` in this case. The following fix will get your test to pass and also have the output be sharded:
<img width="1728" alt="image" src="https://github.com/tenstorrent/tt-metal/assets/109366241/292077ac-a37d-44f0-9c4e-f1364c1dee3c">

There are two issues:
- we need to find a way to add the above fix without breaking existing usage, since there are some models that expects the current behaviour.
- the interleaved output should also work, but it doesn't right now. I am looking into that

**Comment by TT-BrianLiu** [comment]
I identified what was causing the interleaved PCC issue. For sharded inputs, we need to be mindful of the shard orientation when distributing output work. What was happening was input shards are row-major and the work was being distributed col-major (which is the default). 

This PR fixes that and also properly defaults output memory config to the input memory config when nothing is specified: https://github.com/tenstorrent/tt-metal/pull/9939

**Comment by TT-BrianLiu** [comment]
Merged: https://github.com/tenstorrent/tt-metal/pull/9939
